export const samples=[
    {
        version:8,
        tests:
        [
            {   
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/index.html?overview-summary.html', 
            },
            // {   
            //     section:'Index', 
            //     url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/index.html', 
            // },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/jms/package-summary.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/persistence/package-summary.html#index#overview#overview#deprecated', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/deprecated-list.html',  
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/help-doc.html#overview#deprecated', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/overview-tree.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/jms/package-tree.html#index#overview#overview#deprecated', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/servlet/ServletResponseWrapper.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/servlet/ServletRequestWrapper.html#index#overview#overview#deprecated', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/servlet/RequestDispatcher.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/servlet/AsyncContext.html#index#overview#overview#deprecated',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/persistence/LockTimeoutException.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/persistence/OptimisticLockException.html#index#overview#overview#deprecated',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/jms/JMSConnectionFactoryDefinition.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/persistence/TableGenerator.html#index#overview#overview#deprecated',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/persistence/LockModeType.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html?path=liberty-javaee8-javadoc/javax/batch/runtime/Metric.MetricType.html#index#overview#overview#deprecated',     
            },
        ],
    },

    {
        version:7,
        tests:
        [
            {   
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/index.html?overview-summary.html', 
            },
            // {   
            //     section:'Index', 
            //     url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/index-all.html', 
            // },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/jms/package-summary.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/persistence/package-summary.html#index#overview#overview#deprecated', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/help-doc.html#deprecated',  
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/overview-tree.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/jms/package-tree.html#index#overview#overview#deprecated', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/servlet/ServletResponseWrapper.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/servlet/ServletRequestWrapper.html#index#overview#overview#deprecated', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/servlet/RequestDispatcher.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/servlet/AsyncContext.html#index#overview#overview#deprecated',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/persistence/OptimisticLockException.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/persistence/LockTimeoutException.html#index#overview#overview#deprecated',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/jms/JMSConnectionFactoryDefinition.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/persistence/TableGenerator.html#index#overview#overview#deprecated',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/persistence/LockModeType.html#index#overview#overview#deprecated', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee7-javadoc.html?path=liberty-javaee7-javadoc/javax/batch/runtime/Metric.MetricType.html#index#overview#overview#deprecated',     
            },
        ],
    }
]