export const samples=[
    {
        version:'6.1',
        tests:[    
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/index-all.html', 
            },    
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/ws/rs/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/context/spi/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/help-doc.html#package#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/inject/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/inject/spi/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/inject/spi/CDI.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/json/spi/JsonProvider.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/ws/rs/ClientErrorException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/ws/rs/BadRequestException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/annotation/Resource.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/annotation/sql/DataSourceDefinition.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.1-javadoc.html?path=microprofile-6.1-javadoc/jakarta/enterprise/inject/spi/InterceptionType.html',     
            },
        ],
    },  

    {
        version:'6.0',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/ws/rs/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/inject/spi/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/json/spi/JsonProvider.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/inject/spi/CDI.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/inject/spi/BeanManager.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/inject/spi/AfterBeanDiscovery.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/ws/rs/BadRequestException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/ws/rs/ClientErrorException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-6.0-javadoc.html?path=microprofile-6.0-javadoc/jakarta/enterprise/inject/spi/InterceptionType.html',     
            },
        ],
    },

    {
        version:'5.0',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/ws/rs/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/enterprise/inject/spi/package-summary.html', 
            },
            {   
                section:'Deprecated',
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/ws/rs/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/enterprise/inject/spi/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/json/spi/JsonProvider.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/activation/ActivationDataFlavor.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/enterprise/inject/spi/BeanManager.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/enterprise/inject/spi/AfterBeanDiscovery.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/ws/rs/BadRequestException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/ws/rs/ClientErrorException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?path=microprofile-5.0-javadoc/jakarta/enterprise/inject/spi/InterceptionType.html',     
            },
        ],
    },

    {
        version:'4.1',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/ws/rs/package-summary.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/json/spi/JsonProvider.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/interceptor/Interceptor.Priority.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/enterprise/inject/spi/BeanManager.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/ws/rs/ClientErrorException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/ws/rs/BadRequestException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.1-javadoc.html?path=microprofile-4.1-javadoc/javax/enterprise/inject/spi/InterceptionType.html',     
            },
        ],
    },

    {
        version:'4.0',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/ws/rs/package-summary.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/json/spi/JsonProvider.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/interceptor/Interceptor.Priority.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/ws/rs/ClientErrorException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/ws/rs/BadRequestException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-4.0-javadoc.html?path=microprofile-4.0-javadoc/javax/enterprise/inject/spi/InterceptionType.html',     
            },
        ],
    },

    {
        version:'3.3',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/json/spi/JsonProvider.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/interceptor/Interceptor.Priority.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/ws/rs/ClientErrorException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/ws/rs/BadRequestException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html?path=microprofile-3.3-javadoc/javax/enterprise/inject/spi/InterceptionType.html',     
            },
        ],
    },

    {
        version:'3.2',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/json/spi/JsonProvider.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/interceptor/Interceptor.Priority.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/ws/rs/ClientErrorException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/ws/rs/BadRequestException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/enterprise/event/TransactionPhase.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.2-javadoc.html?path=microprofile-3.2-javadoc/javax/enterprise/inject/spi/InterceptionType.html',     
            },    
        ],
    },

    {
        version:'3.0',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/help-doc.html#overview',  
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/json/bind/JsonbConfig.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/org/eclipse/microprofile/reactive/streams/operators/spi/UnsupportedStageException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/javax/json/JsonPatch.Operation.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?path=microprofile-3.0-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },

    {
        version:'2.2',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/json/bind/JsonbConfig.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/json/JsonPatch.Operation.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },

    {
        version:'2.1',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/json/bind/JsonbConfig.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.2-javadoc.html?path=microprofile-2.2-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/javax/json/JsonPatch.Operation.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.1-javadoc.html?path=microprofile-2.1-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },

    {
        version:'2.0',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/help-doc.html#overview',
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/json/bind/JsonbConfig.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/javax/json/JsonPatch.Operation.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-2.0-javadoc.html?path=microprofile-2.0-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },

    {
        version:'1.4',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/help-doc.html#overview',  
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/ws/rs/core/AbstractMultivaluedMap.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/javax/annotation/Resource.AuthenticationType.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.4-javadoc.html?path=microprofile-1.4-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },

    {
        version:'1.3',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/ws/rs/package-summary.html', 
            },
            {   
                section:'Deprecated', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/deprecated-list.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/ws/rs/core/AbstractMultivaluedMap.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/javax/annotation/Resource.AuthenticationType.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.3-javadoc.html?path=microprofile-1.3-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },

    {
        version:'1.2',
        tests:[
            {
                section:'Overview', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/index.html?overview-summary.html', 
            }, 
            {
                section:'Index', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/index-all.html', 
            },
            {
                section:'Packages', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/enterprise/inject/spi/package-summary.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/ws/rs/package-summary.html', 
            },
            {
                section:'Help', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/help-doc.html#overview', 
            },
            {
                section:'Tree', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/enterprise/inject/spi/package-tree.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/ws/rs/package-tree.html', 
            },
            {
                section:'Class', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/json/Json.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/ws/rs/core/AbstractMultivaluedMap.html', 
            },
            {
                section:'Interface', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/enterprise/inject/spi/AfterBeanDiscovery.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/enterprise/inject/spi/BeanManager.html',     
            },    
            {   
                section:'Exception', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/TimeoutException.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/org/eclipse/microprofile/faulttolerance/exceptions/FaultToleranceException.html',     
            },
            {
                section:'Annotation', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/annotation/sql/DataSourceDefinition.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/annotation/Resource.html',     
            },
            {
                section:'Enum', 
                url1:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/javax/annotation/Resource.AuthenticationType.html', 
                url2:'https://openliberty.io/docs/latest/reference/javadoc/microprofile-1.2-javadoc.html?path=microprofile-1.2-javadoc/org/eclipse/microprofile/metrics/MetricType.html',     
            },
        ],
    },
]

export const other_samples=[
    {
        name:'difference-61-60',
        url:'https://openliberty.io/docs/latest/reference/diff/mp-60-61-diff.html',
    },

    {
        name:'difference-60-50',
        url:'https://openliberty.io/docs/latest/reference/diff/mp-50-60-diff.html',
    },

    {
        name:'difference-50-41',
        url:'https://openliberty.io/docs/latest/reference/diff/mp-41-50-diff.html',
    },

    {
        name:'difference-40-33',
        url:'https://openliberty.io/docs/latest/reference/diff/mp-33-40-diff.html',
    },

    {
        name:'difference-30-22',
        url:'https://openliberty.io/docs/latest/reference/diff/mp-22-30-diff.html',
    },

    {
        name:'difference-22-21',
        url:'https://openliberty.io/docs/latest/reference/diff/mp-21-22-diff.html',
    },
];