export const samples=[
    {   
        section:'Overview', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/oauth-2.0.com.ibm.oauth.core.api.attributes.html?path=24.0.0.3/com.ibm.websphere.appserver.api.oauth_1.2-javadoc/index.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/servlet-5.0.com.ibm.websphere.servlet.container.html?path=24.0.0.5/io.openliberty.servlet_1.1-javadoc/index.html', 
    },
    {
        section:'Packages', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/com/ibm/wsspi/cache/package-summary.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/j2eeManagement-1.1.com.ibm.websphere.management.j2ee.html?path=24.0.0.3/com.ibm.websphere.appserver.api.j2eemanagement_1.1-javadoc/com/ibm/websphere/management/j2ee/package-summary.html', 
    },
    {   
        section:'Deprecated', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/deprecated-list.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/servlet-5.0.com.ibm.websphere.servlet.container.html?path=24.0.0.3/io.openliberty.servlet_1.1-javadoc/deprecated-list.html', 
    },
    {
        section:'Help', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/help-doc.html#package', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/appSecurity-2.0.com.ibm.wsspi.security.auth.callback.html?path=24.0.0.3/com.ibm.websphere.appserver.api.security_1.3-javadoc/help-doc.html#package', 
    },
    {
        section:'Tree', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/oauth-2.0.com.ibm.oauth.core.api.attributes.html?path=24.0.0.3/com.ibm.websphere.appserver.api.oauth_1.2-javadoc/overview-tree.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/com/ibm/wsspi/cache/package-tree.html', 
    },
    {
        section:'Class', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/com/ibm/wsspi/cache/Cache.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/j2eeManagement-1.1.com.ibm.websphere.management.j2ee.html?path=24.0.0.3/com.ibm.websphere.appserver.api.j2eemanagement_1.1-javadoc/com/ibm/websphere/management/j2ee/J2EEManagementObjectNameFactory.html', 
    },
    {
        section:'Interface', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/appSecurityClient-1.0.com.ibm.websphere.security.html?path=24.0.0.3/com.ibm.websphere.appserver.api.securityClient_1.1-javadoc/com/ibm/websphere/security/UserRegistry.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/restConnector-2.0.com.ibm.websphere.jmx.connector.rest.html?path=24.0.0.3/com.ibm.websphere.appserver.api.restConnector_1.3-javadoc/com/ibm/websphere/jmx/connector/rest/ConnectorSettings.html',
    },    
    {   
        section:'Exception', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/appSecurityClient-1.0.com.ibm.websphere.security.html?path=24.0.0.3/com.ibm.websphere.appserver.api.securityClient_1.1-javadoc/com/ibm/websphere/security/WSSecurityException.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/appSecurityClient-1.0.com.ibm.websphere.security.html?path=24.0.0.3/com.ibm.websphere.appserver.api.securityClient_1.1-javadoc/com/ibm/websphere/security/CertificateMapFailedException.html', 
    },
    {
        section:'Annotation', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/grpc-1.0.io.openliberty.grpc.annotation.html?path=24.0.0.3/io.openliberty.grpc.1.0_1.0-javadoc/io/openliberty/grpc/annotation/GrpcService.html',  
    },
    {
        section:'Enum', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/j2eeManagement-1.1.com.ibm.websphere.management.j2ee.html?path=24.0.0.3/com.ibm.websphere.appserver.api.j2eemanagement_1.1-javadoc/com/ibm/websphere/management/j2ee/J2EEManagementObjectNameFactory.ResourceType.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/com/ibm/wsspi/cache/CacheConfig.EvictorAlgorithmType.html', 
    },
    {
        section:'Use', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/com/ibm/wsspi/cache/package-use.html',
        url2:'https://openliberty.io/docs/latest/reference/javadoc/api/distributedMap-1.0.com.ibm.wsspi.cache.html?path=24.0.0.3/com.ibm.websphere.appserver.api.distributedMap_2.0-javadoc/com/ibm/wsspi/cache/class-use/CacheConfig.EvictorAlgorithmType.html', 
    },
]