export const samples=[
    {   
        section:'Overview', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.ws.adaptable.module.structure.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/index.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.ws.adaptable.module.structure.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/index.html',
    },
    {
        section:'Packages', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.wsspi.adaptable.module.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/com/ibm/wsspi/adaptable/module/package-summary.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.wsspi.anno.classsource.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/classsource/package-summary.html',
    },
    {   
        section:'Deprecated', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.ws.adaptable.module.structure.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/deprecated-list.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.ws.adaptable.module.structure.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/deprecated-list.html',
    },
    {
        section:'Help', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.wsspi.adaptable.module.adapters.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/help-doc.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.ws.adaptable.module.structure.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/help-doc.html',
    },
    {
        section:'Tree', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.ws.adaptable.module.structure.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/overview-tree.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.wsspi.anno.classsource.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/classsource/package-tree.html',    
    },
    {
        section:'Class', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.wsspi.adaptable.module.html?path=24.0.0.5/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/com/ibm/wsspi/adaptable/module/DefaultNotification.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.wsspi.artifact.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.artifact_1.2-javadoc/com/ibm/wsspi/artifact/DefaultArtifactNotification.html',  
    },
    {
        section:'Interface', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.ws.anno.classsource.specification.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/ws/anno/classsource/specification/ClassSource_Specification_Container.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.wsspi.anno.classsource.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/classsource/ClassSource.html',
    },    
    {   
        section:'Exception', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.wsspi.anno.classsource.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/classsource/ClassSource_Exception.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.wsspi.anno.targets.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/targets/AnnotationTargets_Exception.html',
    },
    {
        section:'Enum', 
        url1:'https://openliberty.io/docs/latest/reference/javadoc/spi/appClientSupport-1.0.com.ibm.wsspi.anno.classsource.html?path=24.0.0.5/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/classsource/ClassSource_ScanCounts.ResultField.html', 
        url2:'https://openliberty.io/docs/latest/reference/javadoc/spi/ejbLite-3.2.com.ibm.wsspi.anno.util.html?path=24.0.0.3/com.ibm.websphere.appserver.spi.anno_1.1-javadoc/com/ibm/wsspi/anno/util/Util_InternMap.ValueType.html',    
    },
]