apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: system
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: system:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        # system probes
        startupProbe:
          httpGet:
            # tag::start1[]
            path: /health/started
            # end::start1[]
            port: 9080
        livenessProbe:
          httpGet:
            # tag::live1[]
            path: /health/live
            # end::live1[]
            port: 9080
          # tag::delay1[]
          initialDelaySeconds: 60
          # end::delay1[]
          # tag::period1[]
          periodSeconds: 10
          # end::period1[]
          # tag::timeout1[]
          timeoutSeconds: 3
          # end::timeout1[]
          # tag::threshold1[]
          failureThreshold: 1
          # end::threshold1[]
        readinessProbe:
          httpGet:
            # tag::ready1[]
            path: /health/ready
            # end::ready1[]
            port: 9080
          # tag::delay2[]
          initialDelaySeconds: 30
          # end::delay2[]
          # tag::period2[]
          periodSeconds: 10
          # end::period2[]
          # tag::timeout2[]
          timeoutSeconds: 3
          # end::timeout2[]
          # tag::threshold2[]
          failureThreshold: 1
          # end::threshold2[]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: inventory:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        env:
        - name: SYS_APP_HOSTNAME
          value: system-service
        # inventory probes
        startupProbe:
          httpGet:
            # tag::start2[]
            path: /health/started
            # end::start2[]
            port: 9080
        livenessProbe:
          httpGet:
            # tag::live2[]
            path: /health/live
            # end::live2[]
            port: 9080
          # tag::delay3[]
          initialDelaySeconds: 60
          # end::delay3[]
          # tag::period3[]
          periodSeconds: 10
          # end::period3[]
          # tag::timeout3[]
          timeoutSeconds: 3
          # end::timeout3[]
          # tag::threshold3[]
          failureThreshold: 1
          # end::threshold3[]
        readinessProbe:
          httpGet:
            # tag::ready2[]
            path: /health/ready
            # end::ready2[]
            port: 9080
          # tag::delay4[]
          initialDelaySeconds: 30
          # end::delay4[]
          # tag::period4[]
          periodSeconds: 10
          # end::period4[]
          # tag::timeout4[]
          timeoutSeconds: 3
          # end::timeout4[]
          # tag::threshold4[]
          failureThreshold: 1
          # end::threshold4[]
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32000
