# Installing and running Jekyll based on: based on https://blog.codeship.com/a-beginners-guide-to-the-dockerfile/
# NodeJS and NPM sections based on: https://gist.github.com/remarkablemark/aacf14c29b3f01d6900d13137b21db3a

# To build this image, from the directory that contains this Dockerfile:
# docker build -f Dockerfile-guides --tag olio/guides .
#
# To run a container:
# docker run --name guides -it -d -p 4000:4000 -v <root directory of a guide git repository on host machine>:/home/jekyll/src/main/content/guides/guide-new olio/guides
#

# The guide will be available at http://localhost:4000/guides/{project-id}.html
# project-id is specified in the guide's README.adoc
#
FROM ruby:2.7.6

# INSTALL NODEJS AND NPM (it's a dependency of something in the Jekyll setup)

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

# nvm environment variables
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 9.0.0

# install nvm
# https://github.com/creationix/nvm#install-script
RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

# install node and npm
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# add node and npm to path so the commands are available
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# confirm installation
RUN node -v
RUN npm -v

# INSTALLING AND RUNNING JEKYLL

# create a user and group for Jekyll, set appropriate permissions, install the Jekyll gem
RUN mkdir -p /home/jekyll \
    && groupadd -rg 1000 jekyll \
    && useradd -rg jekyll -u 1000 -d /home/jekyll jekyll \
    && chown jekyll:jekyll /home/jekyll

#  Set the working directory
WORKDIR /home/jekyll

#Copy files
COPY ./src /home/jekyll/src
COPY ./scripts /home/jekyll/scripts
COPY ./gems /home/jekyll/gems

# openliberty.io gem dependencies
RUN scripts/build/gem_dependencies.sh

# openliberty.io custom gems
RUN pushd gems/ol-target-blank \
    && gem build ol-target-blank.gemspec \
    && gem install ol-target-blank-0.0.1.gem \
    && popd

# Create a mount point where Docker can access a guide on the local system
RUN mkdir -p /home/jekyll/src/main/content/guides/guide-new
RUN git clone https://github.com/OpenLiberty/guides-common.git /home/jekyll/src/main/content/guides/guides-common
VOLUME /home/jekyll/src/main/content/guides/guide-new

# Serve the site
# scripts/jekyll_serve_dev.sh with --force-polling because file change notifications don't work over docker volumes
ENTRYPOINT jekyll s --host 0.0.0.0 --force-polling --future --source src/main/content --config src/main/content/_config.yml,src/main/content/_dev_config.yml --drafts

# Make port 4000 available to the world outside this container
EXPOSE 4000