import { src, dest, parallel, series, watch } from 'gulp'
import gulpSass from 'gulp-sass'
import * as dartSass from 'sass'
const sass = gulpSass(dartSass)
import gulpConnect from 'gulp-connect'

import createTask from './gulp.d/lib/create-task.mjs'
import exportTasks from './gulp.d/lib/export-tasks.mjs'
import * as task from './gulp.d/tasks/index.mjs'

const bundleName = 'ui'
const buildDir = 'build'
const previewSrcDir = 'preview-src'
const previewDestDir = 'public'
const srcDir = 'src'
const destDir = `${previewDestDir}/_`

const livereload = process.env.LIVERELOAD === 'true' ? gulpConnect.reload : undefined
const serverConfig = { host: '0.0.0.0', port: 5252, livereload }

const glob = {
  all: [srcDir, previewSrcDir],
  css: `${srcDir}/css/**/*.css`,
  js: ['gulpfile.mjs', 'gulp.d/**/*.mjs', `${srcDir}/{helpers,js}/**/*.js`],
}

const cleanTask = createTask({
  name: 'clean',
  desc: 'Clean files and folders generated by build',
  call: task.remove(['build', 'public']),
})

const buildTask = createTask({
  name: 'build',
  desc: 'Build and stage the UI assets for bundling',
  call: task.build(srcDir, destDir, process.argv.slice(2).some((name) => name.startsWith('preview'))),
})

const bundleBuildTask = createTask({
  name: 'bundle:build',
  call: series(cleanTask, buildTask),
})

const bundlePackTask = createTask({
  name: 'bundle:pack',
  desc: 'Create a bundle of the staged UI assets for publishing',
  call: task.pack(destDir, buildDir, bundleName),
})

const bundleTask = createTask({
  name: 'bundle',
  desc: 'Clean, build, and bundle the UI for publishing',
  call: series(bundleBuildTask, bundlePackTask),
})

const packTask = createTask({
  name: 'pack',
  desc: '(deprecated; use bundle instead)',
  call: series(bundleTask),
})

const buildPreviewPagesTask = createTask({
  name: 'preview:build-pages',
  call: task.buildPreviewPages(srcDir, previewSrcDir, previewDestDir, livereload),
})

const previewBuildTask = createTask({
  name: 'preview:build',
  desc: 'Process and stage the UI assets and generate pages for the preview',
  call: parallel(buildTask, buildPreviewPagesTask),
})

const previewServeTask = createTask({
  name: 'preview:serve',
  call: task.serve(previewDestDir, serverConfig, () => watch(glob.all, previewBuildTask)),
})

const previewTask = createTask({
  name: 'preview',
  desc: 'Generate a preview site and launch a server to view it',
  call: series(previewBuildTask, previewServeTask),
})

const convertSass = createTask({
  name: 'sass:convert',
  desc: 'Convert scss files to css',
  call: function () {
    return src('./src/sass/**/*.scss')
      .pipe(sass().on('error', sass.logError))
      .pipe(dest('./src/css'))
  }
})

const watchSass = createTask({
  name: 'sass:watch',
  desc: 'Watch for changes to scss files to convert to css',
  call: function(){
    watch('./sass/**/*.scss', convertSass())
  }
})

const tasks = exportTasks(
  bundleTask,
  cleanTask,
  buildTask,
  bundlePackTask,
  previewTask,
  previewBuildTask,
  packTask,
  convertSass,
  watchSass
)

export const bundle = tasks.bundle
export const clean = tasks.clean
export const build = tasks.build
export const bundlePack = tasks['bundle:pack']
export const preview = tasks.preview
export const previewBuild = tasks['preview:build']
export const pack = tasks.pack
export const sassConvert = tasks['sass:convert']
export const sassWatch = tasks['sass:watch']
export default tasks.default || tasks.bundle


