---
layout: post
title:  "JavaOne sessions from the Open Liberty team"
date:   2017-09-29 17:30:00 +0100
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/3322532
---
:description: Come to these JavaOne sessions, or the IBM booth, to hear current and former Liberty developers speak about Open Liberty, MicroProfile, and microservices.
= JavaOne sessions from the Open Liberty team
Laura Cowen <http://github.com/lauracowen>

**Update 2017-10-13**: Now with links to JavaOne session videos, where available.

Wow, how time has flown! It’s been just two weeks since https://openliberty.io/blog/2017/09/19/open-sourcing-liberty.html[Open Liberty went live] and we totally forgot to mention we’ll be at https://www.oracle.com/javaone/index.html[JavaOne] next week. There’ll be a bunch of JavaOne sessions given by Liberty developers (and emeritus developers) throughout the week. If you want to talk to us, come to one of our sessions, seek us out at the IBM booth, or find us at one of the many evening events.

* https://twitter.com/nottycode[Alasdair Nottingham] `#OpenLiberty`
* https://twitter.com/kwsutter[Kevin Sutter] `#MicroProfile #JavaEE`
* https://twitter.com/ian_\_robinson[Ian Robinson] `#OpenLiberty`
* https://twitter.com/gcharters[Graham Charters] `#OpenLiberty #OSGi`
* https://twitter.com/jduimovich[John Duimovich] `#Java`
* https://twitter.com/emilyfhjiang[Emily Jiang] `#MicroProfile #CDI`
* https://twitter.com/geoffpirie[Geoff Pirie] `#OpenLiberty`
* https://twitter.com/megmulsy[Megan Mulholland] `#UX #visualdesign #branding` 
* https://twitter.com/ebullientworks[Erin Schnabel] (emeritus) `#OpenLiberty #microservices`
* https://twitter.com/KateStanley91[Kate Stanley] (emeritus)  `#OpenLiberty #microservices`
* https://twitter.com/holly_cummins[Holly Cummins] (emeritus)  `#OpenLiberty #IoT #JavaChampion`

## JavaOne sessions featuring Liberty developers

So, where will you find Liberty developers?

### Monday

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con8030&showEnrolled=false[Opening up Java EE: Panel discussion with Oracle, IBM, Red Hat, and the Eclipse Foundation] +
Ian Robinson - 4.30pm +
https://youtu.be/BkJt7IjL3XM[video]

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con7714&showEnrolled=false[WebSphere Liberty meets open source] +
Alasdair Nottingham, Ian Robinson – 5.30pm

### Tuesday

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con1896&showEnrolled=false[Cloud-native Java done right] +
Alasdair Nottingham, Kevin Sutter – 3pm

### Wednesday

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con1825&showEnrolled=false[Panel: Accelerating the adoption of Java EE 8 with MicroProfile] +
Kevin Sutter – 11.45am +
https://youtu.be/BhMLxwf0AMM[video]

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con2417&showEnrolled=false[Java versus Node.js versus Swift in the Language Performance Olympics] +
Graham Charters – 1.45pm

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con3730&showEnrolled=false[Jump-start your microservices development with Java EE] +
Kate Stanley, Graham Charters – 1.45pm +
https://youtu.be/1HdtILoL6O4[video]

### Thursday

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=%22java%20community%20keynote%20reloaded%22&showEnrolled=false[Java, open technologies, and cloud-native development: The next generation of innovation emerges] +
John Duimovich, Ian Robinson - 9am +
http://video.oracle.com/detail/videos/most-recent/video/5600375079001/ibm-javaone-keynote-10-5-2017?autoStart=true[video]

## Some JavaOne sessions featuring former Liberty developers
	
And if that isn’t enough for you, some of these sessions might be of interest to you:

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=HOL7896&showEnrolled=false[Introduction to Reactive Systems] +
Erin Schnabel – 4.30pm

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con1756&showEnrolled=false[Choosing a NoSQL API and database to avoid tombstones and dragons in Game On!] +
Erin Schnabel – Wednesday 12.45pm

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con2930&showEnrolled=false[Thinking strategically about IoT] +
Holly Cummins – Wednesday 4.30pm

https://events.rainfocus.com/catalog/oracle/oow17/catalogjavaone17?search=con3222&showEnrolled=false[So You Say You Want a Chatbot Revolution] +
Holly Cummins – Thursday 1.45pm

## Talk to them on the booths and get free stuff

If you drop by the IBM Open Liberty, IBM MicroProfile, and IBM Game On! booths, several current and former Liberty developers will be hanging out there. Come and chat to them. They’d love to meet you! And they might even have free t-shirts and other goodies to share…
