---
layout: post
title:  "Open Sourcing Liberty"
date:   2017-07-25 15:53:42 -0400
categories: news
---
= Open Sourcing Liberty
Alasdair Nottingham <http://github.com/nottycode>

I’d like to take this opportunity to welcome you to the Open Liberty project.

In 2012, IBM released WebSphere Liberty, an application server designed for the cloud. It was small, lightweight, and designed with modern application development in mind. It wasn’t perfect, it didn’t have everything people wanted, but it was a great start. Since then we have expanded Liberty to make it fully Java EE 7 certified, and we have deployed it to every major developer platform, including is Docker, Kubernetes, and Cloud Foundry. Liberty has been deployed successfully at a large number of our customers and continues to be rolled out. However, in this industry nothing stays still and the bar is constantly moving.

Over the last year we have had a lot of discussions with developers about how Liberty needs to evolve in order to meet developers' expectations, and to continue innovating to support modern application needs. Of course, what ‘modern’ means in this context is always changing and microservices are redefining how software is developed. This is why we have been so active in the http://microprofile.io[Eclipse MicroProfile] project which is helping to create common APIs for writing cloud-native Java applications.

It isn’t just about what we do, though, it is also how we do it. Talking with developers we have often been asked if we have any plans to open source Liberty. Well the answer is yes. The open source core of WebSphere Liberty is now available on https://github.com/openliberty/open-liberty[GitHub] under the EPL v1 license. You can find out more and download the latest nightly builds on the new http://www.openliberty.io[OpenLiberty.io] website. We have a new mailing list on https://groups.io/g/openliberty[Groups.io] for discussion and we will also be answering questions on https://stackoverflow.com/questions/tagged/open-liberty[Stack Overflow].

The Open Liberty project is a fully compatible Java EE 7 application server and, of course, it includes the latest http://microprofile.io[Eclipse MicroProfile] APIs too. It forms the core of the commercial WebSphere Liberty product which will be built from the Open Liberty source code with no changes, so an application that runs on Open Liberty will run unchanged on WebSphere Liberty. And if you need support, you can get that through WebSphere Liberty too.

Taking a successful software project and transitioning to open source is not easy. While many of us in the WebSphere development team have been regular contributors to open source projects this is a massive shift in how we do things and our development culture. We will be learning as we go, with the support of experienced open source developers in IBM, as well as the wider open source community. In the spirit of openness, we will share what we learn as we go. We know that there will be times when we will get things wrong, but we think Liberty is the best and most flexible runtime for server-side Java and are delighted to be open sourcing it today. We invite anyone who wants to make it even better to get involved to help us make the Open Liberty project a success as well.
