distributionUrl=https://na.artifactory.swg-devops.com:443/artifactory/wasliberty-maven-remote-cache/org/apache/maven/apache-maven/3.9.0/apache-maven-3.9.0-bin.zip
wrapperUrl=https://na.artifactory.swg-devops.com:443/artifactory/wasliberty-maven-remote-cache/io/takari/m2e/workspace/org.eclipse.m2e.workspace.cli/0.4.0/org.eclipse.m2e.workspace.cli-0.4.0.jar
