# Maven distribution URL - points to JFrog Artifactory
distributionUrl=https://na.artifactory.swg-devops.com:443/artifactory/wasliberty-maven-remote-cache/org/apache/maven/apache-maven/3.9.0/apache-maven-3.9.0-bin.zip

# Maven wrapper JAR URL - Using Maven Wrapper 3.2.0
wrapperUrl=https://na.artifactory.swg-devops.com/artifactory/wasliberty-maven-remote/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar
