:page-layout: intro
:page-description: Intro to MicroProfile
:page-categories: MicroProfile
:page-permalink: /docs/intro/microprofile.html
= Introduction to MicroProfile

https://microprofile.io/[Eclipse MicroProfile] is a modular set of technologies designed for writing cloud-native Java microservices. This introduction will give you an understanding of how MicroProfile helps with developing and managing cloud-native microservices.  The https://openliberty.io/guides/[Open Liberty MicroProfile guides] give you first-hand experience of using MicroProfile to build microservices with Open Liberty.

== MicroProfile and cloud-native Java microservices

Cloud-native is an industry-wide approach to developing and rapidly deploying applications to the cloud at scale. Cloud-native applications are designed around team-aligned microservices and developed using agile practices and continuous integration/continuous delivery to streamline deployment. With a range of vendors providing cloud platforms, avoiding vendor lock-in is key and open source and open standards are essential enablers for avoiding this.

MicroProfile enables you to develop and deploy cloud-native Java applications as loosely-coupled, lightweight services, each representing one unique business function. This approach is modular and makes the application easy to understand, easy to develop, easy to test, and easy to maintain.

== Microservice architecture

Microservice architecture is a popular approach for building cloud-native applications such that each component is an individual service fulfilling a specific purpose. It enables small, autonomous teams to develop, deploy, and scale their respective services independently. One benefit is that the application can be scaled on a more granular level, because each service is built and managed independently. The high-traffic services can be individually scaled to efficiently use resources rather than scaling up the entire system. Another benefit is that failures in one service can be isolated from the rest of the system; if a service fails, services that are independent are unaffected whilst dependent services can employ fault tolerance strategies to prevent the failure from cascading to other services.

While providing many benefits, a microservice architecture also introduces new challenges not apparent in traditional monolithic applications. MicroProfile's purpose is to address these challenges to make it simple and easy to develop cloud-native applications.  These challenges includes toleration of service failures, end-to-end security for an authenticated user request flowing through a set of microservices and problem determination for requests spanning many services.

=== MicroProfile simplifies developing cloud-native Java microservices

The vast majority of cloud-native microservices are based on REST APIs  At its foundation, MicroProfile provides a set of technologies that make developing and using REST APIs easy. MicroProfile takes a small set of Java EE APIs: JAX-RS; CDI; JSON-B and JSON-P and augments them with a simple type-safe REST client API making it easy to consume REST services.

*TODO: I'm not sure these two sections add much. I'd either delete them, or ideally have sections that expand on each of the individual specs.  If we think we can't get to that by Friday, let's raise an issue to do it later.*

==== Build RESTful web services
The JAX-RS, CDI, JSON-B and JSON-P Java EE technologies provide the base for MicroProfile. If you're new to Java EE and MicroProfile, this is a good place to start.

==== Consuming a RESTful web service with type-safe Java
MicroProfile Rest Client provides a type-safe approach for invoking RESTful services over HTTP.  This API greatly simplifies the client-side API as defined by JAX-RS. MicroProfile Rest Client handles the communication between the client and service.

=== MicroProfile simplifies scaling your organization

Handling hundreds of autonomous, collaborating and frequently evolving services introduces a number of new challenges.  For example, documenting and sharing APIs across teams, propagation of security across services, handling network or service failures, and frequent and rapid continuous integration and continuous deployment of service updates.  Thankfully, MicroProfile provides a number of APIs to simplify these tasks. 

==== Document your RESTful APIs
MicroProfile OpenAPI provides a Java API for the OpenAPI specification that you can use to expose API documentation for your RESTful APIs.  You can natively produce OpenAPI documents from your JAX-RS applications. OpenAPI is a standardization of https://swagger.io/blog/difference-between-swagger-and-openapi/[the Swagger specification].

==== Handle unexpected failures in your microservices
MicroProfile Fault Tolerance provides an API and annotations for building robust behavior to cope with unexpected failures in the service you depend on.  Aspects of fault-tolerant execution include timeouts, retries, fallbacks, bulkhead processing, and circuit breakers.

==== Authentication and role-based access control
MicroProfile JWT provides for interoperable authentication and role-based access control for your services.  It allows for an authenticated JWT token to be shared across multiple microservices--even if these services are running on multiple vendors’ implementations and for access to microservice operations to be controlled based on user and role information passed within the JWT token.

==== Externalize configuration to improve portability
MicroProfile Config externalizes configuration from the application to improve portability of the application. A core principle is to be able to override configuration at deployment time using system properties and environment variables. This means you can build your microservice once and deploy it many times through your CI/CD pipeline by changing the configuration for each deployment.

=== MicroProfile helps you detect and diagnose problems

Handling hundreds of microservices requires a strong operations focus. If the system is beginning to exhibit problems, how do you track down the root cause when a request might span tens or hundreds of services?  How can you tell which service is not performing well, or understand the journey a request took through those microservices?  MicroProfile helps you answer these questions by providing APIs to help you understand the health of services, how they're performing, and how requests are flowing through them.

==== Determine a microservice's availability
MicroProfile Health Check provides a common REST endpoint format to determine whether a microservice is healthy or not. Health can be determined by the service itself and might be based on the availability of necessary resources (e.g. a database) and services.  The service itself might be running but considered unhealthly if the things it requires for normal execution are unavailable.  The Health Check endpoints are also designed to be easily integrated into Kubernetes liveness and readiness probes.

==== Monitor a microservice's telemetry data
MicroProfile Metrics provides common REST endpoints for monitoring a running microservice's telemetry data. Similar in nature to JMX but a much simpler API using JAX-RS.  Both built-in and application-defined metrics are accessible, with the output in either JSON or Prometheus text formats. This API provides more extensive detail than the simple up/down reporting provided by MicroProfile Health.

==== Enable distributed tracing of your microservices
MicroProfile OpenTracing allows services to easily participate in a distributed tracing environment.  OpenTracing defines behaviors and an API for accessing an http://opentracing.io/[OpenTracing]-compliant Tracer object within your microservice.  These trace logs can then be consumed by a third-party distributed tracing facility such as https://zipkin.io/[Zipkin] or https://github.com/jaegertracing/jaeger[Jaeger].
