#!/bin/bash

KAFKA_SERVER=kafka:9092
NETWORK=reactive-app

docker network create $NETWORK

docker run -d \
	-e ALLOW_ANONYMOUS_LOGIN=yes \
	--name=zookeeper \
	--network=$NETWORK \
	--rm \
	bitnami/zookeeper:3

docker run -d \
	-e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181 \
	-e ALLOW_PLAINTEXT_LISTENER=yes \
	-e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
	--name=kafka \
	--hostname=kafka \
	--network=$NETWORK \
	--rm \
	bitnami/kafka:2

docker run -d \
	-e KAFKA_SERVER=$KAFKA_SERVER \
	-e GROUP_ID=system-client-group \
	--name=system-service \
	--network=$NETWORK \
	--rm \
	system:1.0-SNAPSHOT

docker run -d \
	-e KAFKA_SERVER=$KAFKA_SERVER \
	-e GROUP_ID_PREFIX=system-properties \
	--name=inventory-service \
	--network=$NETWORK \
	--rm \
	inventory:1.0-SNAPSHOT

docker run -d \
	-e KAFKA_SERVER=$KAFKA_SERVER \
	-e GROUP_ID_PREFIX=job \
	--name=job-service \
	--network=$NETWORK \
	--rm \
	job:1.0-SNAPSHOT

docker run -d \
	--name=gateway \
	--hostname=gateway \
	-p 8080:9080 \
	--network=$NETWORK \
	--rm \
	gateway:1.0-SNAPSHOT

