= Application Client Support for Server 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables the Liberty server to process client modules and support remote client containers.

== Enabling this feature
To enable the Application Client Support for Server 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>appClientSupport-1.0</feature>
----

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Application Client Support for Server 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.appClientSupport-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jndi-1.0[]

== Features that enable this feature
* feature:javaee-7.0[]
* feature:javaee-8.0[]

== Feature configuration elements
* config:application[]
* config:applicationManager[]
* config:applicationMonitor[]
* config:channelfw[]
* config:classloading[]
* config:enterpriseApplication[]
* config:iiopEndpoint[]
* config:iiopServerPolicies[]
* config:javaPermission[]
* config:library[]
* config:orb[]
* config:tcpOptions[]
* config:webApplication[]
