= Application Security 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature is superseded by appSecurity-2.0. Support for securing the server runtime environment and applications. This feature enables servlet-3.0 and web application security, support for LDAP and basic user registries, and SSL. To support secure EJB applications, you must add the ejbLite-3.1 feature. When you add this feature to your server, you need to configure a user registry, such as the basic user registry or the LDAP user registry. 

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Application Security 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>appSecurity-1.0</feature>
----
// end::enable[]
// tag::superceeded[]

== Features that this feature is superseded by
* feature:ldapRegistry-3.0[]
* feature:appSecurity-2.0[]
// end::superceeded[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:appSecurity-2.0[]
* feature:ldapRegistry-3.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]

== Features that enable this feature
* feature:passwordUtilities-1.0[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Application Security 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.appSecurity-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
