= Cloudant Integration 1.0
:stylesheet: ../feature.css
:linkcss: 
:nofooter: 

This feature enables connections to Cloudant by providing a connector instance configured in the server configuration, which can be injected or accessed through JNDI.  Applications use the Cloudant client library to utilize the connector instance.

== Enabling this feature
To enable the Cloudant Integration 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>cloudant-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Cloudant Integration 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.cloudant-1.0; type="osgi.subsystem.feature"
----

== Feature configuration elements
* config:authData[]
* config:classloading[]
* config:cloudant[]
* config:cloudantDatabase[]
* config:library[]
