= CouchDB Integration 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables connections to CouchDB by providing a connector instance configured in the server configuration, which can be injected or accessed through JNDI.  Applications use the ektorp client library to utilize the connector instance to work with CouchDB.

== Enabling this feature
To enable the CouchDB Integration 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>couchdb-1.0</feature>
----

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the CouchDB Integration 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.couchdb-1.0; type="osgi.subsystem.feature"
----

== Feature configuration elements
* config:classloading[]
* config:couchdb[]
* config:library[]
