= Enterprise JavaBeans 3.2
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables support for Enterprise JavaBeans written to the EJB 3.2 specification.

== Enabling this feature
To enable the Enterprise JavaBeans 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>ejb-3.2</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Enterprise JavaBeans 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.ejb-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:ejbHome-3.2[]
* feature:ejbLite-3.2[]
* feature:ejbPersistentTimer-3.2[]
* feature:ejbRemote-3.2[]
* feature:jdbc-4.1[]
* feature:jdbc-4.2[]
* feature:mdb-3.2[]

== Features that enable this feature
* feature:javaee-7.0[]
* feature:javaee-8.0[]

== Feature configuration elements
* config:classloading[]
* config:transaction[]
