= Enterprise JavaBeans Home Interfaces 3.2
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables the use of home interfaces in Enterprise JavaBeans.

== Enabling this feature
To enable the Enterprise JavaBeans Home Interfaces 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>ejbHome-3.2</feature>
----

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Enterprise JavaBeans Home Interfaces 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.ejbHome-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:ejbLite-3.2[]

== Features that enable this feature
* feature:ejb-3.2[]

== Feature configuration elements
* config:classloading[]
* config:transaction[]
