= Java Authorization Contract for Containers 1.5
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables support for Java Authorization Contract for Containers (JACC) version 1.5 In order to add the jacc-1.5 feature to your server, you need to add the third party JACC provider which is not a part of the WebSphere Application Server Liberty profile.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Java Authorization Contract for Containers 1.5 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jacc-1.5</feature>
----
// end::enable[]
// tag::config[]

== Feature configuration elements
* config:classloading[]
// end::config[]
// tag::apis[]

== Standard API packages provided by this feature
* javadoc:javax.security.jacc[]

== IBM API packages provided by this feature
* javadoc:com.ibm.wsspi.security.authorization.jacc[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:appSecurity-2.0[]
* feature:appSecurity-3.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]

== Features that enable this feature
* feature:javaee-7.0[]
* feature:javaee-8.0[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Authorization Contract for Containers 1.5 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jacc-1.5; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
