= Java Authentication SPI for Containers 1.1
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables support for securing the server runtime environment and applications using Java Authentication SPI for Containers (JASPIC) providers as defined in JSR-196

== Enabling this feature
To enable the Java Authentication SPI for Containers 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jaspic-1.1</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Authentication SPI for Containers 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jaspic-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:appSecurity-2.0[]
* feature:appSecurity-3.0[]

== Features that enable this feature
* feature:javaee-7.0[]
* feature:webProfile-8.0[]

== Standard API packages provided by this feature
* javadoc:javax.security.auth.message[]
* javadoc:javax.security.auth.message.callback[]
* javadoc:javax.security.auth.message.config[]
* javadoc:javax.security.auth.message.module[]

== SPI packages provided by this feature
* javadoc:com.ibm.wsspi.security.jaspi[]

== Feature configuration elements
* config:classloading[]
* config:library[]
