= Java RESTful Services 2.1
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables support for Java API for RESTful Web Services v2.1.  JAX-RS annotations can be used to define web service clients and endpoints that comply with the REST architectural style. Endpoints are accessed through a common interface that is based on the HTTP standard methods.

== Enabling this feature
To enable the Java RESTful Services 2.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jaxrs-2.1</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java RESTful Services 2.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jaxrs-2.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jaxrsClient-2.1[]
* feature:servlet-4.0[]

== Features that enable this feature
* feature:microProfile-1.2[]
* feature:microProfile-1.3[]
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]
* feature:mpOpenAPI-1.0[]
* feature:mpOpenTracing-1.0[]
* feature:mpOpenTracing-1.1[]
* feature:opentracing-1.0[]
* feature:opentracing-1.1[]
* feature:webProfile-8.0[]

== Feature configuration elements
* config:classloading[]
* config:library[]
* config:webTarget[]
