= Java RESTful Services 2.0
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables support for Java API for RESTful Web Services.  JAX-RS annotations can be used to define web service clients and endpoints that comply with the REST architectural style. Endpoints are accessed through a common interface that is based on the HTTP standard methods.

== Enabling this feature
To enable the Java RESTful Services 2.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jaxrs-2.0</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java RESTful Services 2.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jaxrs-2.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jaxrsClient-2.0[]
* feature:json-1.0[]
* feature:servlet-3.1[]

== Features that enable this feature
* feature:microProfile-1.0[]
* feature:microProfile-1.2[]
* feature:microProfile-1.3[]
* feature:microProfile-1.4[]
* feature:mpOpenAPI-1.0[]
* feature:mpOpenTracing-1.0[]
* feature:mpOpenTracing-1.1[]
* feature:mpOpenTracing-1.2[]
* feature:opentracing-1.0[]
* feature:opentracing-1.1[]
* feature:opentracing-1.2[]
* feature:webProfile-7.0[]

== Feature configuration elements
* config:classloading[]
* config:library[]
* config:webTarget[]
