= Java Database Connectivity 4.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables the configuration of DataSources to access Databases from applications. Any database that complies with the JDBC 4.0 specification can be used; customized configuration of many specific providers is included. High performance connection pooling is also provided.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Java Database Connectivity 4.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jdbc-4.0</feature>
----
// end::enable[]
// tag::config[]

== Feature configuration elements
* config:authData[]
* config:classloading[]
* config:connectionManager[]
* config:dataSource[]
* config:jdbcDriver[]
* config:library[]
* config:transaction[]
// end::config[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:jndi-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]

== Features that enable this feature
* feature:batch-1.0[]
* feature:sessionDatabase-1.0[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Database Connectivity 4.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jdbc-4.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
