= JMS Message-Driven Beans 3.2
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature is superseded by mdb-3.2. Both features provide identical function; only the feature names are different. mdb-3.2 is the preferred feature name.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the JMS Message-Driven Beans 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jmsMdb-3.2</feature>
----
// end::enable[]
// tag::superceeded[]

== Features that this feature is superseded by
* feature:mdb-3.2[]
// end::superceeded[]
// tag::config[]

== Feature configuration elements
* config:classloading[]
* config:transaction[]
// end::config[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:mdb-3.2[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JMS Message-Driven Beans 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jmsMdb-3.2; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
