= Java Persistence API Container 2.2
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables support for applications that use application-managedand container-managed JPA written to the Java Persistence API 2.2 specification.  This only includes Java Persistence API 2.2 specification interfaces, and container-managedJPA integration.  This feature does not include any JPA implementation.

== Enabling this feature
To enable the Java Persistence API Container 2.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jpaContainer-2.2</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Persistence API Container 2.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jpaContainer-2.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jdbc-4.2[]
* feature:jndi-1.0[]

== Features that enable this feature
* feature:jpa-2.2[]

== Standard API packages provided by this feature
* javadoc:javax.persistence[]
* javadoc:javax.persistence.criteria[]
* javadoc:javax.persistence.metamodel[]
* javadoc:javax.persistence.spi[]

== Feature configuration elements
* config:classloading[]
* config:jpa[]
* config:library[]
* config:transaction[]
