= JavaServer Faces Container 2.3
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables CDI integrations for web applications that use the Java Server Faces (JSF) 2.3 framework. This feature only includes container integration code for JSF, and does not include any JSF interfaces or implementation.  To use this feature, JSF interfaces and implementation must be packaged within web applications that use JSF.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the JavaServer Faces Container 2.3 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jsfContainer-2.3</feature>
----
// end::enable[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:cdi-2.0[]
* feature:jndi-1.0[]
* feature:jsp-2.3[]
* feature:servlet-4.0[]
* feature:websocket-1.1[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaServer Faces Container 2.3 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jsfContainer-2.3; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
