= JavaScript Object Notation Processing 1.1 via Bells
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
The Java API for JSON Processing (JSON-P) feature provides a standardized method for constructing and manipulating data to be rendered in JavaScript Object Notation (JSON). When this feature is enabled, there is no built-in JSON-P provider. Instead, configure a JSON-P provider via a <bell> which points at a library containing the JSON-P provider JAR file(s).

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the JavaScript Object Notation Processing 1.1 via Bells feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jsonpContainer-1.1</feature>
----
// end::enable[]
// tag::apis[]

== Standard API packages provided by this feature
* javadoc:javax.json[]
* javadoc:javax.json.spi[]
* javadoc:javax.json.stream[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:bells-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaScript Object Notation Processing 1.1 via Bells feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jsonpContainer-1.1; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
