= JavaScript Object Notation for Java 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature provides access to the JavaScript Object Notation (JSON4J) library. The JSON4J library provides a simple Java model for constructing and manipulating data to be rendered as JSON data.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the JavaScript Object Notation for Java 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>json-1.0</feature>
----
// end::enable[]
// tag::apis[]

== IBM API packages provided by this feature
* javadoc:com.ibm.json.java[]
* javadoc:com.ibm.json.xml[]
// end::apis[]
// tag::requirements[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]

== Features that enable this feature
* feature:audit-1.0[]
* feature:jaxrs-2.0[]
* feature:jaxrsClient-2.0[]
* feature:mpHealth-1.0[]
* feature:mpMetrics-1.0[]
* feature:mpMetrics-1.1[]
* feature:restConnector-2.0[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaScript Object Notation for Java 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.json-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
