= JavaScript Object Notation Processing 1.1
:linkcss: 
:page-layout: feature
:nofooter: 

The Java API for JSON Processing (JSON-P) feature provides a standardized method for constructing and manipulating data to be rendered in JavaScript Object Notation (JSON).

== Enabling this feature
To enable the JavaScript Object Notation Processing 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jsonp-1.1</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaScript Object Notation Processing 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jsonp-1.1; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:javaeeClient-8.0[]
* feature:jaxrsClient-2.1[]
* feature:jsonb-1.0[]
* feature:jsonbContainer-1.0[]
* feature:jwtSso-1.0[]
* feature:microProfile-1.2[]
* feature:microProfile-1.3[]
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]
* feature:microProfile-2.1[]
* feature:mpJwt-1.0[]
* feature:mpJwt-1.1[]
* feature:mpRestClient-1.0[]
* feature:mpRestClient-1.1[]
* feature:socialLogin-1.0[]
* feature:webProfile-8.0[]

== Standard API packages provided by this feature
* javadoc:javax.json[]
* javadoc:javax.json.spi[]
* javadoc:javax.json.stream[]
