= JavaScript Object Notation Binding 1.0
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

The Java API for JSON Binding (JSON-B) feature provides a standard for converting between Java objects and JavaScript Object Notation (JSON).

== Enabling this feature
To enable the JavaScript Object Notation Binding 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jsonb-1.0</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaScript Object Notation Binding 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jsonb-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jsonp-1.1[]

== Features that enable this feature
* feature:javaeeClient-8.0[]
* feature:microProfile-2.0[]
* feature:webProfile-8.0[]

== Standard API packages provided by this feature
* javadoc:javax.json.bind[]
* javadoc:javax.json.bind.adapter[]
* javadoc:javax.json.bind.annotation[]
* javadoc:javax.json.bind.config[]
* javadoc:javax.json.bind.serializer[]
* javadoc:javax.json.bind.spi[]

== Feature configuration elements
* config:classloading[]
* config:library[]
