= JSON Web Token Single Sign-On 1.0
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

This feature allows the runtime to produce and consume MP-JWT cookies for authentication.

== Enabling this feature
To enable the JSON Web Token Single Sign-On 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jwtSso-1.0</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JSON Web Token Single Sign-On 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jwtSso-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:appSecurity-2.0[]
* feature:jsonp-1.0[]
* feature:jsonp-1.1[]
* feature:jwt-1.0[]
* feature:servlet-3.1[]
* feature:servlet-4.0[]

== Feature configuration elements
* config:authFilter[]
* config:jwtSso[]
* config:mpJwt[]
