= Message-Driven Beans 3.2
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables the use of Message-Driven Enterprise JavaBeans written to the EJB 3.2 specification. MDBs allow asynchronous processing of messages within a Java EE component.

== Enabling this feature
To enable the Message-Driven Beans 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mdb-3.2</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Message-Driven Beans 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mdb-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jca-1.7[]
* feature:jndi-1.0[]

== Features that enable this feature
* feature:ejb-3.2[]
* feature:jmsMdb-3.2[]

== Feature configuration elements
* config:application[]
* config:applicationManager[]
* config:applicationMonitor[]
* config:classloading[]
* config:ejbApplication[]
* config:ejbContainer[]
* config:enterpriseApplication[]
* config:javaPermission[]
* config:library[]
* config:transaction[]
* config:webApplication[]
