= MicroProfile 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature combines the Liberty features that support Eclipse MicroProfile 1.0 for Cloud Native Java.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the MicroProfile 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>microProfile-1.0</feature>
----
// end::enable[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:cdi-1.2[]
* feature:jaxrs-2.0[]
* feature:jsonp-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.microProfile-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
