= MicroProfile 2.0
:linkcss: 
:page-layout: feature
:nofooter: 

This feature combines the Liberty features that support Eclipse MicroProfile 2.0 for Cloud Native Java.

== Enabling this feature
To enable the MicroProfile 2.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>microProfile-2.0</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile 2.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.microProfile-2.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-2.0[]
* feature:jaxrs-2.1[]
* feature:jaxrsClient-2.1[]
* feature:jsonb-1.0[]
* feature:jsonp-1.1[]
* feature:mpConfig-1.3[]
* feature:mpFaultTolerance-1.1[]
* feature:mpHealth-1.0[]
* feature:mpJwt-1.1[]
* feature:mpMetrics-1.1[]
* feature:mpOpenAPI-1.0[]
* feature:mpOpenTracing-1.1[]
* feature:mpRestClient-1.1[]
* feature:servlet-4.0[]
