= MicroProfile 1.3
:linkcss: 
:page-layout: feature
:nofooter: 

This feature combines the Liberty features that support Eclipse MicroProfile 1.3 for Cloud Native Java.

== Enabling this feature
To enable the MicroProfile 1.3 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>microProfile-1.3</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile 1.3 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.microProfile-1.3; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[]
* feature:cdi-2.0[]
* feature:jaxrs-2.0[]
* feature:jaxrs-2.1[]
* feature:jaxrsClient-2.0[]
* feature:jaxrsClient-2.1[]
* feature:jsonp-1.0[]
* feature:jsonp-1.1[]
* feature:mpConfig-1.2[]
* feature:mpFaultTolerance-1.0[]
* feature:mpHealth-1.0[]
* feature:mpJwt-1.0[]
* feature:mpMetrics-1.1[]
* feature:mpOpenAPI-1.0[]
* feature:mpOpenTracing-1.0[]
* feature:mpRestClient-1.0[]
* feature:servlet-3.1[]
* feature:servlet-4.0[]
