= MongoDB Integration 2.0
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables the usage of the MongoDB Java Driver and allows DB instances to be configured in the server configuration, injected into managed components such as EJBs, and accessed through JNDI. Applications interact with these DB instances via the MongoDB APIs

== Enabling this feature
To enable the MongoDB Integration 2.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mongodb-2.0</feature>
----

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MongoDB Integration 2.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mongodb-2.0; type="osgi.subsystem.feature"
----

== Feature configuration elements
* config:classloading[]
* config:library[]
* config:mongo[]
* config:mongoDB[]
