= MicroProfile Config 1.1
:linkcss: 
:page-layout: feature
:nofooter: 

The Eclipse MicroProfile Config specification provides a unified mechanism to access configuration, providing a single view of multiple sources.

== Enabling this feature
To enable the MicroProfile Config 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpConfig-1.1</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile Config 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpConfig-1.1; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:microProfile-1.2[]
* feature:mpFaultTolerance-1.0[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.config[]
* javadoc:org.eclipse.microprofile.config.inject[]
* javadoc:org.eclipse.microprofile.config.spi[]

== Feature configuration elements
* config:classloading[]
