= MicroProfile Config 1.3
:linkcss: 
:page-layout: feature
:nofooter: 

The Eclipse MicroProfile Config specification provides a unified mechanism to access configuration, providing a single view of multiple sources.

== Enabling this feature
To enable the MicroProfile Config 1.3 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpConfig-1.3</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile Config 1.3 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpConfig-1.3; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]
* feature:microProfile-2.1[]
* feature:mpFaultTolerance-1.1[]
* feature:mpJwt-1.1[]
* feature:mpMetrics-1.1[]
* feature:mpOpenAPI-1.0[]
* feature:opentracing-1.2[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.config[]
* javadoc:org.eclipse.microprofile.config.inject[]
* javadoc:org.eclipse.microprofile.config.spi[]

== Feature configuration elements
* config:application[]
* config:applicationManager[]
* config:applicationMonitor[]
* config:classloading[]
* config:library[]
