= MicroProfile Fault Tolerance 1.1
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

This feature provides support for the Eclipse MicroProfile Fault Tolerance 1.1 specification.

== Enabling this feature
To enable the MicroProfile Fault Tolerance 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpFaultTolerance-1.1</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile Fault Tolerance 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpFaultTolerance-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:concurrent-1.0[]
* feature:mpConfig-1.3[]

== Features that enable this feature
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.faulttolerance[]
* javadoc:org.eclipse.microprofile.faulttolerance.exceptions[]
