= MicroProfile Health 1.0
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

This feature provides support for the Eclipse MicroProfile Health specification.

== Enabling this feature
To enable the MicroProfile Health 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpHealth-1.0</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile Health 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpHealth-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[]
* feature:cdi-2.0[]
* feature:jndi-1.0[]
* feature:json-1.0[]
* feature:servlet-3.1[]
* feature:servlet-4.0[]

== Features that enable this feature
* feature:microProfile-1.2[]
* feature:microProfile-1.3[]
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.health[]
* javadoc:org.eclipse.microprofile.health.spi[]
