= MicroProfile OpenTracing 1.1
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

The MicroProfile OpenTracing specification provides a mechanism to access an opentracing.io Tracer.

== Enabling this feature
To enable the MicroProfile OpenTracing 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpOpenTracing-1.1</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile OpenTracing 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpOpenTracing-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[]
* feature:cdi-2.0[]
* feature:jaxrs-2.0[]
* feature:jaxrs-2.1[]
* feature:opentracing-1.1[]

== Features that enable this feature
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.opentracing[]
