= MicroProfile Rest Client 1.1
:linkcss: 
:page-layout: feature
:nofooter: 

The MicroProfile Rest Client specification provides a type-safe mechanism for invoking RESTful services.

== Enabling this feature
To enable the MicroProfile Rest Client 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpRestClient-1.1</feature>
----

== Supported Java versions

* JavaSE-1.8
* JavaSE-9.0

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile Rest Client 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpRestClient-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jaxrsClient-2.0[]
* feature:jaxrsClient-2.1[]
* feature:jsonp-1.0[]
* feature:jsonp-1.1[]

== Features that enable this feature
* feature:microProfile-1.4[]
* feature:microProfile-2.0[]
* feature:microProfile-2.1[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.rest.client[]
* javadoc:org.eclipse.microprofile.rest.client.annotation[]
* javadoc:org.eclipse.microprofile.rest.client.ext[]
* javadoc:org.eclipse.microprofile.rest.client.inject[]
* javadoc:org.eclipse.microprofile.rest.client.spi[]
