= OSGi Debug Console 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables an OSGi console to aid debug of the runtime. It can  be used to display information about bundles, packages and services which may be useful when developing your own features for product extensions.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the OSGi Debug Console 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>osgiConsole-1.0</feature>
----
// end::enable[]
// tag::apis[]
// end::apis[]
// tag::requirements[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the OSGi Debug Console 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.osgiConsole-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
