= Password Utilities 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables support for obtaining the values of the user and password attributes of authData elements from an application, and also allows the use of the com.ibm.websphere.crypto.PasswordUtil class as an API.

== Enabling this feature
To enable the Password Utilities 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>passwordUtilities-1.0</feature>
----

== Supported Java versions

* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Password Utilities 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.passwordUtilities-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:appSecurity-1.0[]
* feature:appSecurity-2.0[]
* feature:appSecurity-3.0[]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.crypto[]
* javadoc:com.ibm.websphere.security.auth.data[]
* javadoc:com.ibm.websphere.security.jca[]

== Feature configuration elements
* config:authData[]
* config:classloading[]
* config:jaasLoginContextEntry[]
* config:jaasLoginModule[]
* config:transaction[]
