= Admin REST Connector 2.0
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

A secure admin connector that can be used locally or remotely using any JDK. It enables remote access by clients via a REST-based connector and requires SSL and basic user security configuration. Client support includes JMX. This feature supersedes the restConnector-1.0 feature and does not include the jaxrs-1.1 feature.

== Enabling this feature
To enable the Admin REST Connector 2.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>restConnector-2.0</feature>
----

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Admin REST Connector 2.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.restConnector-2.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:distributedMap-1.0[]
* feature:json-1.0[]
* feature:ssl-1.0[]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.filetransfer[]
* javadoc:com.ibm.websphere.jmx.connector.rest[]
* javadoc:com.ibm.ws.jmx.connector.client.rest[]

== Feature configuration elements
* config:administrator-role[]
* config:authCache[]
* config:authentication[]
* config:authorization-roles[]
* config:basicRegistry[]
* config:channelfw[]
* config:classloading[]
* config:httpAccessLogging[]
* config:httpDispatcher[]
* config:httpEncoding[]
* config:httpEndpoint[]
* config:httpOptions[]
* config:httpProxyRedirect[]
* config:jaasLoginContextEntry[]
* config:jaasLoginModule[]
* config:library[]
* config:ltpa[]
* config:mimeTypes[]
* config:quickStartSecurity[]
* config:remoteFileAccess[]
* config:tcpOptions[]
* config:trustAssociation[]
* config:virtualHost[]
