= Micro Profile 1.3
:nofooter:
This feature combines the Liberty features that support Micro Profile 1.3 for Cloud Native Java.

== Enabling this feature
To enable the Micro Profile 1.3 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>microProfile-1.3</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Micro Profile 1.3 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.microProfile-1.3; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[cdi-1.2]
* feature:jaxrs-2.0[jaxrs-2.0]
* feature:jsonp-1.0[jsonp-1.0]
* feature:mpConfig-1.2[mpConfig-1.2]
* feature:mpFaultTolerance-1.0[mpFaultTolerance-1.0]
* feature:mpHealth-1.0[mpHealth-1.0]
* feature:mpJwt-1.0[mpJwt-1.0]
* feature:mpMetrics-1.1[mpMetrics-1.1]
* feature:mpOpenAPI-1.0[mpOpenAPI-1.0]
* feature:mpOpenTracing-1.0[mpOpenTracing-1.0]
* feature:mpRestClient-1.0[mpRestClient-1.0]
* feature:servlet-3.1[servlet-3.1]
