= Enterprise JavaBeans Persistent Timers 3.2
:nofooter:
This feature enables the use of persistent timers in Enterprise JavaBeans.

== Enabling this feature
To enable the Enterprise JavaBeans Persistent Timers 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>ejbPersistentTimer-3.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Enterprise JavaBeans Persistent Timers 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.ejbPersistentTimer-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:ejbLite-3.2[ejbLite-3.2]
* feature:jdbc-4.1[jdbc-4.1]
* feature:jdbc-4.2[jdbc-4.2]
* feature:jndi-1.0[jndi-1.0]

== Features that enable this feature
* feature:ejb-3.2[ejb-3.2]

== Feature configuration elements
* config:classloading[classloading]
* config:databaseStore[databaseStore]
* config:persistentExecutor[persistentExecutor]
* config:transaction[transaction]
