= Application Client Support for Server
:nofooter:
This feature enables the Liberty server to process client modules and support remote client containers.

== Enabling this feature
To enable the Application Client Support for Server feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>appClientSupport-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Application Client Support for Server feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.appClientSupport-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jndi-1.0[jndi-1.0]

== Features that enable this feature
* feature:javaee-7.0[javaee-7.0]

== Feature configuration elements
* config:application[application]
* config:applicationManager[applicationManager]
* config:applicationMonitor[applicationMonitor]
* config:channelfw[channelfw]
* config:classloading[classloading]
* config:enterpriseApplication[enterpriseApplication]
* config:iiopEndpoint[iiopEndpoint]
* config:iiopServerPolicies[iiopServerPolicies]
* config:javaPermission[javaPermission]
* config:library[library]
* config:orb[orb]
* config:tcpOptions[tcpOptions]
* config:webApplication[webApplication]
