= Java RESTful Services Client 2.0
:nofooter:
This feature enables support for Java Client API for JAX-RS 2.0.

== Enabling this feature
To enable the Java RESTful Services Client 2.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jaxrsClient-2.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java RESTful Services Client 2.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jaxrsClient-2.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:json-1.0[json-1.0]
* feature:servlet-3.1[servlet-3.1]

== Features that enable this feature
* feature:jaxrs-2.0[jaxrs-2.0]
* feature:mpRestClient-1.0[mpRestClient-1.0]

== Feature configuration elements
* config:classloading[classloading]
* config:library[library]
* config:webTarget[webTarget]
