= Concurrency Utilities for Java EE 1.0
:nofooter:
This feature enables the creation of managed executors that allow applications to submit tasks to run concurrently, with thread context that is managed by the application server.It also enables the creation of managed thread factories to create threads that run with the threadcontext of the component that looks up the managed thread factory.

== Enabling this feature
To enable the Concurrency Utilities for Java EE 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>concurrent-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Concurrency Utilities for Java EE 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.concurrent-1.0; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:javaee-7.0[javaee-7.0]
* feature:mpFaultTolerance-1.0[mpFaultTolerance-1.0]

== Standard API packages provided by this feature
* javadoc:javax.enterprise.concurrent[javax.enterprise.concurrent]

== Feature configuration elements
* config:classloading[classloading]
* config:concurrencyPolicy[concurrencyPolicy]
* config:contextService[contextService]
* config:managedExecutorService[managedExecutorService]
* config:managedScheduledExecutorService[managedScheduledExecutorService]
* config:managedThreadFactory[managedThreadFactory]
