= Java Database Connectivity 4.0
:nofooter:
This feature enables the configuration of DataSources to access Databases from applications. Any database that complies with the JDBC 4.0 specification can be used; customized configuration of many specific providers is included. High performance connection pooling is also provided.

== Enabling this feature
To enable the Java Database Connectivity 4.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jdbc-4.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Database Connectivity 4.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jdbc-4.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jndi-1.0[jndi-1.0]

== Features that enable this feature
* feature:batch-1.0[batch-1.0]
* feature:sessionDatabase-1.0[sessionDatabase-1.0]

== Feature configuration elements
* config:authData[authData]
* config:classloading[classloading]
* config:connectionManager[connectionManager]
* config:dataSource[dataSource]
* config:jdbcDriver[jdbcDriver]
* config:library[library]
* config:transaction[transaction]
