= Enterprise JavaBeans 3.2
:nofooter:
This feature enables support for Enterprise JavaBeans written to the EJB 3.2 specification.

== Enabling this feature
To enable the Enterprise JavaBeans 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>ejb-3.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Enterprise JavaBeans 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.ejb-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:ejbHome-3.2[ejbHome-3.2]
* feature:ejbLite-3.2[ejbLite-3.2]
* feature:ejbPersistentTimer-3.2[ejbPersistentTimer-3.2]
* feature:ejbRemote-3.2[ejbRemote-3.2]
* feature:jdbc-4.1[jdbc-4.1]
* feature:jdbc-4.2[jdbc-4.2]
* feature:mdb-3.2[mdb-3.2]

== Features that enable this feature
* feature:javaee-7.0[javaee-7.0]

== Feature configuration elements
* config:classloading[classloading]
* config:transaction[transaction]
