= JavaScript Object Notation Processing 1.0
:nofooter:
The Java API for JSON Processing (JSON-P) feature provides a standardized method for constructing and manipulating data to be rendered in JavaScript Object Notation (JSON).

== Enabling this feature
To enable the JavaScript Object Notation Processing 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jsonp-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaScript Object Notation Processing 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jsonp-1.0; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:javaeeClient-7.0[javaeeClient-7.0]
* feature:microProfile-1.0[microProfile-1.0]
* feature:microProfile-1.2[microProfile-1.2]
* feature:microProfile-1.3[microProfile-1.3]
* feature:mpJwt-1.0[mpJwt-1.0]
* feature:mpRestClient-1.0[mpRestClient-1.0]
* feature:webProfile-7.0[webProfile-7.0]

== Standard API packages provided by this feature
* javadoc:javax.json[javax.json]
* javadoc:javax.json.spi[javax.json.spi]
* javadoc:javax.json.stream[javax.json.stream]
