= MicroProfile Fault Tolerance 1.0
:nofooter:
This feature provides support for the MicroProfile Fault Tolerance API for enterprise Java.

== Enabling this feature
To enable the MicroProfile Fault Tolerance 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpFaultTolerance-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile Fault Tolerance 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpFaultTolerance-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:concurrent-1.0[concurrent-1.0]
* feature:mpConfig-1.1[mpConfig-1.1]
* feature:mpConfig-1.2[mpConfig-1.2]

== Features that enable this feature
* feature:microProfile-1.2[microProfile-1.2]
* feature:microProfile-1.3[microProfile-1.3]
