= Bean Validation 1.1
:nofooter:
The Bean Validation 1.1 specification provides an annotation based model for validating JavaBeans.  It can be used to assert and maintain the integrity of data as it travels through an application. This feature is built on top of Apache BVal.

== Enabling this feature
To enable the Bean Validation 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>beanValidation-1.1</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Bean Validation 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.beanValidation-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:el-3.0[el-3.0]

== Features that enable this feature
* feature:javaeeClient-7.0[javaeeClient-7.0]
* feature:webProfile-7.0[webProfile-7.0]

== Standard API packages provided by this feature
* javadoc:javax.validation[javax.validation]
* javadoc:javax.validation.bootstrap[javax.validation.bootstrap]
* javadoc:javax.validation.constraints[javax.validation.constraints]
* javadoc:javax.validation.constraintvalidation[javax.validation.constraintvalidation]
* javadoc:javax.validation.executable[javax.validation.executable]
* javadoc:javax.validation.groups[javax.validation.groups]
* javadoc:javax.validation.metadata[javax.validation.metadata]
* javadoc:javax.validation.spi[javax.validation.spi]

== Feature configuration elements
* config:classloading[classloading]
* config:library[library]
* config:transaction[transaction]
