= Java Connector Architecture Security Inflow
:nofooter:
This feature enables security inflow for resource adapters.

== Enabling this feature
To enable the Java Connector Architecture Security Inflow feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jcaInboundSecurity-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Connector Architecture Security Inflow feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jcaInboundSecurity-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:ssl-1.0[ssl-1.0]

== Features that enable this feature
* feature:javaee-7.0[javaee-7.0]

== Standard API packages provided by this feature
* javadoc:javax.security.auth.message.callback[javax.security.auth.message.callback]

== Feature configuration elements
* config:administrator-role[administrator-role]
* config:authCache[authCache]
* config:authentication[authentication]
* config:basicRegistry[basicRegistry]
* config:classloading[classloading]
* config:jaasLoginContextEntry[jaasLoginContextEntry]
* config:jaasLoginModule[jaasLoginModule]
* config:library[library]
* config:ltpa[ltpa]
* config:quickStartSecurity[quickStartSecurity]
* config:transaction[transaction]
