= Java Authorization Contract for Containers 1.5
:nofooter:
This feature enables support for Java Authorization Contract for Containers (JACC) version 1.5 In order to add the jacc-1.5 feature to your server, you need to add the third party JACC provider which is not a part of the WebSphere Application Server Liberty profile.

== Enabling this feature
To enable the Java Authorization Contract for Containers 1.5 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jacc-1.5</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Authorization Contract for Containers 1.5 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jacc-1.5; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:appSecurity-2.0[appSecurity-2.0]

== Features that enable this feature
* feature:javaee-7.0[javaee-7.0]

== Standard API packages provided by this feature
* javadoc:javax.security.jacc[javax.security.jacc]

== IBM API packages provided by this feature
* javadoc:com.ibm.wsspi.security.authorization.jacc[com.ibm.wsspi.security.authorization.jacc]

== Feature configuration elements
* config:classloading[classloading]
