= Message-Driven Beans 3.2
:nofooter:
This feature enables the use of Message-Driven Enterprise JavaBeans written to the EJB 3.2 specification. MDBs allow asynchronous processing of messages within a Java EE component.

== Enabling this feature
To enable the Message-Driven Beans 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mdb-3.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Message-Driven Beans 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mdb-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jca-1.7[jca-1.7]
* feature:jndi-1.0[jndi-1.0]

== Features that enable this feature
* feature:ejb-3.2[ejb-3.2]
* feature:jmsMdb-3.2[jmsMdb-3.2]

== Feature configuration elements
* config:application[application]
* config:applicationManager[applicationManager]
* config:applicationMonitor[applicationMonitor]
* config:classloading[classloading]
* config:ejbApplication[ejbApplication]
* config:ejbContainer[ejbContainer]
* config:enterpriseApplication[enterpriseApplication]
* config:javaPermission[javaPermission]
* config:library[library]
* config:transaction[transaction]
* config:webApplication[webApplication]
