= Java Database Connectivity 4.1
:nofooter:
This feature enables the configuration of DataSources to access Databases from applications. Any JDBC driver that complies with the JDBC 4.1, 4.0, 3.0, or 2.x specification can be used; customized configuration of many specific providers is included. High performance connection pooling is also provided.

== Enabling this feature
To enable the Java Database Connectivity 4.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jdbc-4.1</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Database Connectivity 4.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jdbc-4.1; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:batch-1.0[batch-1.0]
* feature:ejb-3.2[ejb-3.2]
* feature:ejbPersistentTimer-3.2[ejbPersistentTimer-3.2]
* feature:javaee-7.0[javaee-7.0]
* feature:javaeeClient-7.0[javaeeClient-7.0]
* feature:jpa-2.1[jpa-2.1]
* feature:jpaContainer-2.1[jpaContainer-2.1]
* feature:sessionDatabase-1.0[sessionDatabase-1.0]
* feature:webProfile-7.0[webProfile-7.0]

== Feature configuration elements
* config:authData[authData]
* config:classloading[classloading]
* config:connectionManager[connectionManager]
* config:dataSource[dataSource]
* config:jdbcDriver[jdbcDriver]
* config:library[library]
* config:transaction[transaction]
