= JavaScript Object Notation Processing 1.1 via Bells
:stylesheet: ../feature.css
:linkcss: 
:nofooter: 

The Java API for JSON Processing (JSON-P) feature provides a standardized method for constructing and manipulating data to be rendered in JavaScript Object Notation (JSON). When this feature is enabled, there is no built-in JSON-P provider. Instead, configure a JSON-P provider via a <bell> which points at a library containing the JSON-P provider JAR file(s).

== Enabling this feature
To enable the JavaScript Object Notation Processing 1.1 via Bells feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jsonpContainer-1.1</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JavaScript Object Notation Processing 1.1 via Bells feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jsonpContainer-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:bells-1.0[]

== Standard API packages provided by this feature
* javadoc:javax.json[]
* javadoc:javax.json.spi[]
* javadoc:javax.json.stream[]
