= JMS Message-Driven Beans 3.2
:nofooter:
This feature is superseded by mdb-3.2. Both features provide identical function; only the feature names are different. mdb-3.2 is the preferred feature name.

== Enabling this feature
To enable the JMS Message-Driven Beans 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jmsMdb-3.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the JMS Message-Driven Beans 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jmsMdb-3.2; type="osgi.subsystem.feature"
----

== Features that this feature is superseded by
* feature:mdb-3.2[mdb-3.2]

== Features that this feature enables
* feature:mdb-3.2[mdb-3.2]

== Feature configuration elements
* config:classloading[classloading]
* config:transaction[transaction]
