= Java WebSocket 1.1
:nofooter:
This feature enables support for WebSocket applications written to the Java API for WebSocket 1.1 specification.

== Enabling this feature
To enable the Java WebSocket 1.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>websocket-1.1</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java WebSocket 1.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.websocket-1.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:servlet-3.1[servlet-3.1]

== Features that enable this feature
* feature:webProfile-7.0[webProfile-7.0]

== Standard API packages provided by this feature
* javadoc:javax.websocket[javax.websocket]
* javadoc:javax.websocket.server[javax.websocket.server]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.wsoc[com.ibm.websphere.wsoc]

== Feature configuration elements
* config:wsocOutbound[wsocOutbound]
