= Java XML Bindings 2.2
:nofooter:
This feature enables support for the Java Architecture for XML Binding 2.2 specification, which provides easy mapping of Java classes to XML documents.

== Enabling this feature
To enable the Java XML Bindings 2.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jaxb-2.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java XML Bindings 2.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jaxb-2.2; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:javaeeClient-7.0[javaeeClient-7.0]
* feature:jaxws-2.2[jaxws-2.2]

== Standard API packages provided by this feature
* javadoc:javax.xml.bind[javax.xml.bind]
* javadoc:javax.xml.bind.annotation[javax.xml.bind.annotation]
* javadoc:javax.xml.bind.annotation.adapters[javax.xml.bind.annotation.adapters]
* javadoc:javax.xml.bind.attachment[javax.xml.bind.attachment]
* javadoc:javax.xml.bind.helpers[javax.xml.bind.helpers]
* javadoc:javax.xml.bind.util[javax.xml.bind.util]

== Feature configuration elements
* config:classloading[classloading]
* config:library[library]
