= Distributed Map interface for Dynamic Caching
:nofooter:
This feature provides a local cache service which can be accessed through the DistributedMap API. A default cache is bound in JNDI at "services/cache/distributedmap". Caches can be distributed through addition of a network cache provider such as WebSphere eXtreme Scale.

== Enabling this feature
To enable the Distributed Map interface for Dynamic Caching feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>distributedMap-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Distributed Map interface for Dynamic Caching feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.distributedMap-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jndi-1.0[jndi-1.0]

== Features that enable this feature
* feature:jwt-1.0[jwt-1.0]
* feature:mpMetrics-1.0[mpMetrics-1.0]
* feature:mpMetrics-1.1[mpMetrics-1.1]
* feature:restConnector-2.0[restConnector-2.0]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.cache[com.ibm.websphere.cache]
* javadoc:com.ibm.websphere.cache.exception[com.ibm.websphere.cache.exception]
* javadoc:com.ibm.websphere.exception[com.ibm.websphere.exception]
* javadoc:com.ibm.ws.cache.spi[com.ibm.ws.cache.spi]
* javadoc:com.ibm.wsspi.cache[com.ibm.wsspi.cache]

== Feature configuration elements
* config:classloading[classloading]
* config:distributedMap[distributedMap]
* config:library[library]
