= Java Persistence API Container 2.1
:nofooter:
This feature enables support for applications that use application-managedand container-managed JPA written to the Java Persistence API 2.1 specification.  This only includes Java Persistence API 2.1 specification interfaces, and container-managedJPA integration.  This feature does not include any JPA implementation.

== Enabling this feature
To enable the Java Persistence API Container 2.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jpaContainer-2.1</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Persistence API Container 2.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jpaContainer-2.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jdbc-4.1[jdbc-4.1]
* feature:jdbc-4.2[jdbc-4.2]

== Features that enable this feature
* feature:jpa-2.1[jpa-2.1]

== Standard API packages provided by this feature
* javadoc:javax.persistence[javax.persistence]
* javadoc:javax.persistence.criteria[javax.persistence.criteria]
* javadoc:javax.persistence.metamodel[javax.persistence.metamodel]
* javadoc:javax.persistence.spi[javax.persistence.spi]

== Feature configuration elements
* config:classloading[classloading]
* config:jpa[jpa]
* config:library[library]
* config:transaction[transaction]
