= Micro Profile Json Web Token 1.0
:stylesheet: ../feature.css
:linkcss: 
:nofooter: 

This feature enables web applications or microservices to use JSON Web Token (JWT) to authenticate users instead of, or in addition to, the configured user registry.

== Enabling this feature
To enable the Micro Profile Json Web Token 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpJwt-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Micro Profile Json Web Token 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpJwt-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[]
* feature:cdi-2.0[]
* feature:jsonp-1.0[]
* feature:jsonp-1.1[]
* feature:jwt-1.0[]
* feature:servlet-3.1[]
* feature:servlet-4.0[]

== Features that enable this feature
* feature:microProfile-1.2[]
* feature:microProfile-1.3[]

== Stable API packages provided by this feature
* javadoc:org.eclipse.microprofile.auth[]
* javadoc:org.eclipse.microprofile.jwt[]

== Feature configuration elements
* config:mpJwt[]
