= Micro Profile 1.2
:stylesheet: ../feature.css
:linkcss: 
:nofooter: 

This feature combines the Liberty features that support Micro Profile 1.2 for Cloud Native Java.

== Enabling this feature
To enable the Micro Profile 1.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>microProfile-1.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Micro Profile 1.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.microProfile-1.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[]
* feature:cdi-2.0[]
* feature:jaxrs-2.0[]
* feature:jaxrs-2.1[]
* feature:jsonp-1.0[]
* feature:jsonp-1.1[]
* feature:mpConfig-1.1[]
* feature:mpFaultTolerance-1.0[]
* feature:mpHealth-1.0[]
* feature:mpJwt-1.0[]
* feature:mpMetrics-1.0[]
* feature:servlet-3.1[]
* feature:servlet-4.0[]
