= Micro Profile Json Web Token 1.0
:nofooter:
This feature enables web applications or microservices to use JSON Web Token (JWT) to authenticate users instead of, or in addition to, the configured user registry.

== Enabling this feature
To enable the Micro Profile Json Web Token 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpJwt-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Micro Profile Json Web Token 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpJwt-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:cdi-1.2[cdi-1.2]
* feature:jsonp-1.0[jsonp-1.0]
* feature:jwt-1.0[jwt-1.0]
* feature:servlet-3.1[servlet-3.1]

== Features that enable this feature
* feature:microProfile-1.2[microProfile-1.2]
* feature:microProfile-1.3[microProfile-1.3]

== Feature configuration elements
* config:mpJwt[mpJwt]
