= Message Server 1.0
:nofooter:
This feature enables an embedded messaging server that is JMS compliant. Applications can send and receive messages using the wasJmsClient feature.

== Enabling this feature
To enable the Message Server 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>wasJmsServer-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Message Server 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.wasJmsServer-1.0; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:javaee-7.0[javaee-7.0]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.messaging.mbean[com.ibm.websphere.messaging.mbean]

== Feature configuration elements
* config:channelfw[channelfw]
* config:classloading[classloading]
* config:messagingEngine[messagingEngine]
* config:tcpOptions[tcpOptions]
* config:transaction[transaction]
* config:wasJmsEndpoint[wasJmsEndpoint]
* config:wasJmsOutbound[wasJmsOutbound]
