= Performance Monitoring
:nofooter:
This feature enables the Performance Monitoring Infrastructure (PMI) for other features the server is running. Monitoring data is accessible through standard MXBeans; access through the traditional WebSphere Perf MBean can be enabled.

== Enabling this feature
To enable the Performance Monitoring feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>monitor-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Performance Monitoring feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.monitor-1.0; type="osgi.subsystem.feature"
----

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.monitor.jmx[com.ibm.websphere.monitor.jmx]

== Feature configuration elements
* config:classloading[classloading]
* config:monitor[monitor]
