= MicroProfile OpenAPI 1.0
:nofooter:
This feature provides support for the MicroProfile OpenAPI for enterprise Java.

== Enabling this feature
To enable the MicroProfile OpenAPI 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>mpOpenAPI-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the MicroProfile OpenAPI 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.mpOpenAPI-1.0; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jaxrs-2.0[jaxrs-2.0]
* feature:mpConfig-1.2[mpConfig-1.2]
* feature:servlet-3.1[servlet-3.1]

== Features that enable this feature
* feature:microProfile-1.3[microProfile-1.3]

== SPI packages provided by this feature
* javadoc:org.eclipse.microprofile.openapi.spi[org.eclipse.microprofile.openapi.spi]
