= Enterprise JavaBeans Lite 3.2
:nofooter:
This feature enables support for Enterprise JavaBeans written to the EJB Lite subset of the EJB 3.2 specification.

== Enabling this feature
To enable the Enterprise JavaBeans Lite 3.2 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>ejbLite-3.2</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Enterprise JavaBeans Lite 3.2 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.ejbLite-3.2; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jndi-1.0[jndi-1.0]

== Features that enable this feature
* feature:ejb-3.2[ejb-3.2]
* feature:ejbHome-3.2[ejbHome-3.2]
* feature:ejbPersistentTimer-3.2[ejbPersistentTimer-3.2]
* feature:ejbRemote-3.2[ejbRemote-3.2]
* feature:webProfile-7.0[webProfile-7.0]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.ejbcontainer.mbean[com.ibm.websphere.ejbcontainer.mbean]

== Feature configuration elements
* config:application[application]
* config:applicationManager[applicationManager]
* config:applicationMonitor[applicationMonitor]
* config:classloading[classloading]
* config:ejbApplication[ejbApplication]
* config:ejbContainer[ejbContainer]
* config:enterpriseApplication[enterpriseApplication]
* config:javaPermission[javaPermission]
* config:library[library]
* config:transaction[transaction]
* config:webApplication[webApplication]
