= Java Naming and Directory Interface
:nofooter:
This feature enables the use of Java Naming and Directory Interface (JNDI) to access server configured resources such as DataSources or JMS Connection Factories. It also allows access to Java primitives configured in the server as a jndiEntry.

== Enabling this feature
To enable the Java Naming and Directory Interface feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jndi-1.0</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Naming and Directory Interface feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jndi-1.0; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:appClientSupport-1.0[appClientSupport-1.0]
* feature:batch-1.0[batch-1.0]
* feature:distributedMap-1.0[distributedMap-1.0]
* feature:ejbLite-3.2[ejbLite-3.2]
* feature:ejbPersistentTimer-3.2[ejbPersistentTimer-3.2]
* feature:javaeeClient-7.0[javaeeClient-7.0]
* feature:jdbc-4.0[jdbc-4.0]
* feature:jpa-2.1[jpa-2.1]
* feature:jsfContainer-2.2[jsfContainer-2.2]
* feature:managedBeans-1.0[managedBeans-1.0]
* feature:mdb-3.2[mdb-3.2]
* feature:mpHealth-1.0[mpHealth-1.0]
* feature:sessionDatabase-1.0[sessionDatabase-1.0]
* feature:webProfile-7.0[webProfile-7.0]

== Feature configuration elements
* config:classloading[classloading]
* config:jndiEntry[jndiEntry]
* config:jndiObjectFactory[jndiObjectFactory]
* config:jndiReferenceEntry[jndiReferenceEntry]
* config:jndiURLEntry[jndiURLEntry]
* config:library[library]
