= Java Persistence API 2.1
:nofooter:
This feature enables support for applications that use application-managed and container-managed JPA written to the Java Persistence API 2.1 specification. The support is built on top of EclipseLink to support the container-managed programming model.

== Enabling this feature
To enable the Java Persistence API 2.1 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>jpa-2.1</feature>
----

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Java Persistence API 2.1 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.jpa-2.1; type="osgi.subsystem.feature"
----

== Features that this feature enables
* feature:jdbc-4.1[jdbc-4.1]
* feature:jdbc-4.2[jdbc-4.2]
* feature:jndi-1.0[jndi-1.0]
* feature:jpaContainer-2.1[jpaContainer-2.1]

== Features that enable this feature
* feature:javaeeClient-7.0[javaeeClient-7.0]
* feature:webProfile-7.0[webProfile-7.0]

== Third-party API packages provided by this feature
* javadoc:org.eclipse.persistence[org.eclipse.persistence]
* javadoc:org.eclipse.persistence.annotations[org.eclipse.persistence.annotations]
* javadoc:org.eclipse.persistence.config[org.eclipse.persistence.config]
* javadoc:org.eclipse.persistence.core.descriptors[org.eclipse.persistence.core.descriptors]
* javadoc:org.eclipse.persistence.core.mappings[org.eclipse.persistence.core.mappings]
* javadoc:org.eclipse.persistence.core.mappings.converters[org.eclipse.persistence.core.mappings.converters]
* javadoc:org.eclipse.persistence.core.queries[org.eclipse.persistence.core.queries]
* javadoc:org.eclipse.persistence.core.sessions[org.eclipse.persistence.core.sessions]
* javadoc:org.eclipse.persistence.descriptors[org.eclipse.persistence.descriptors]
* javadoc:org.eclipse.persistence.descriptors.copying[org.eclipse.persistence.descriptors.copying]
* javadoc:org.eclipse.persistence.descriptors.invalidation[org.eclipse.persistence.descriptors.invalidation]
* javadoc:org.eclipse.persistence.descriptors.partitioning[org.eclipse.persistence.descriptors.partitioning]
* javadoc:org.eclipse.persistence.dynamic[org.eclipse.persistence.dynamic]
* javadoc:org.eclipse.persistence.eis[org.eclipse.persistence.eis]
* javadoc:org.eclipse.persistence.eis.interactions[org.eclipse.persistence.eis.interactions]
* javadoc:org.eclipse.persistence.eis.mappings[org.eclipse.persistence.eis.mappings]
* javadoc:org.eclipse.persistence.exceptions[org.eclipse.persistence.exceptions]
* javadoc:org.eclipse.persistence.exceptions.i18n[org.eclipse.persistence.exceptions.i18n]
* javadoc:org.eclipse.persistence.expressions[org.eclipse.persistence.expressions]
* javadoc:org.eclipse.persistence.expressions.spatial[org.eclipse.persistence.expressions.spatial]
* javadoc:org.eclipse.persistence.history[org.eclipse.persistence.history]
* javadoc:org.eclipse.persistence.internal.cache[org.eclipse.persistence.internal.cache]
* javadoc:org.eclipse.persistence.internal.codegen[org.eclipse.persistence.internal.codegen]
* javadoc:org.eclipse.persistence.internal.core.databaseaccess[org.eclipse.persistence.internal.core.databaseaccess]
* javadoc:org.eclipse.persistence.internal.core.descriptors[org.eclipse.persistence.internal.core.descriptors]
* javadoc:org.eclipse.persistence.internal.core.helper[org.eclipse.persistence.internal.core.helper]
* javadoc:org.eclipse.persistence.internal.core.queries[org.eclipse.persistence.internal.core.queries]
* javadoc:org.eclipse.persistence.internal.core.sessions[org.eclipse.persistence.internal.core.sessions]
* javadoc:org.eclipse.persistence.internal.databaseaccess[org.eclipse.persistence.internal.databaseaccess]
* javadoc:org.eclipse.persistence.internal.descriptors.changetracking[org.eclipse.persistence.internal.descriptors.changetracking]
* javadoc:org.eclipse.persistence.internal.dynamic[org.eclipse.persistence.internal.dynamic]
* javadoc:org.eclipse.persistence.internal.expressions[org.eclipse.persistence.internal.expressions]
* javadoc:org.eclipse.persistence.internal.helper[org.eclipse.persistence.internal.helper]
* javadoc:org.eclipse.persistence.internal.helper.linkedlist[org.eclipse.persistence.internal.helper.linkedlist]
* javadoc:org.eclipse.persistence.internal.history[org.eclipse.persistence.internal.history]
* javadoc:org.eclipse.persistence.internal.indirection[org.eclipse.persistence.internal.indirection]
* javadoc:org.eclipse.persistence.internal.jpa[org.eclipse.persistence.internal.jpa]
* javadoc:org.eclipse.persistence.internal.jpa.deployment[org.eclipse.persistence.internal.jpa.deployment]
* javadoc:org.eclipse.persistence.internal.jpa.deployment.xml.parser[org.eclipse.persistence.internal.jpa.deployment.xml.parser]
* javadoc:org.eclipse.persistence.internal.jpa.jdbc[org.eclipse.persistence.internal.jpa.jdbc]
* javadoc:org.eclipse.persistence.internal.jpa.jpql[org.eclipse.persistence.internal.jpa.jpql]
* javadoc:org.eclipse.persistence.internal.jpa.metadata[org.eclipse.persistence.internal.jpa.metadata]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.accessors[org.eclipse.persistence.internal.jpa.metadata.accessors]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.accessors.classes[org.eclipse.persistence.internal.jpa.metadata.accessors.classes]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.accessors.mappings[org.eclipse.persistence.internal.jpa.metadata.accessors.mappings]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.accessors.objects[org.eclipse.persistence.internal.jpa.metadata.accessors.objects]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.additionalcriteria[org.eclipse.persistence.internal.jpa.metadata.additionalcriteria]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.cache[org.eclipse.persistence.internal.jpa.metadata.cache]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.changetracking[org.eclipse.persistence.internal.jpa.metadata.changetracking]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.columns[org.eclipse.persistence.internal.jpa.metadata.columns]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.converters[org.eclipse.persistence.internal.jpa.metadata.converters]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.copypolicy[org.eclipse.persistence.internal.jpa.metadata.copypolicy]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.inheritance[org.eclipse.persistence.internal.jpa.metadata.inheritance]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.listeners[org.eclipse.persistence.internal.jpa.metadata.listeners]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.locking[org.eclipse.persistence.internal.jpa.metadata.locking]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.mappings[org.eclipse.persistence.internal.jpa.metadata.mappings]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.multitenant[org.eclipse.persistence.internal.jpa.metadata.multitenant]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.nosql[org.eclipse.persistence.internal.jpa.metadata.nosql]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.partitioning[org.eclipse.persistence.internal.jpa.metadata.partitioning]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.queries[org.eclipse.persistence.internal.jpa.metadata.queries]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.sequencing[org.eclipse.persistence.internal.jpa.metadata.sequencing]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.structures[org.eclipse.persistence.internal.jpa.metadata.structures]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.tables[org.eclipse.persistence.internal.jpa.metadata.tables]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.transformers[org.eclipse.persistence.internal.jpa.metadata.transformers]
* javadoc:org.eclipse.persistence.internal.jpa.metadata.xml[org.eclipse.persistence.internal.jpa.metadata.xml]
* javadoc:org.eclipse.persistence.internal.jpa.metamodel[org.eclipse.persistence.internal.jpa.metamodel]
* javadoc:org.eclipse.persistence.internal.jpa.parsing[org.eclipse.persistence.internal.jpa.parsing]
* javadoc:org.eclipse.persistence.internal.jpa.parsing.jpql[org.eclipse.persistence.internal.jpa.parsing.jpql]
* javadoc:org.eclipse.persistence.internal.jpa.parsing.jpql.antlr[org.eclipse.persistence.internal.jpa.parsing.jpql.antlr]
* javadoc:org.eclipse.persistence.internal.jpa.querydef[org.eclipse.persistence.internal.jpa.querydef]
* javadoc:org.eclipse.persistence.internal.jpa.transaction[org.eclipse.persistence.internal.jpa.transaction]
* javadoc:org.eclipse.persistence.internal.jpa.weaving[org.eclipse.persistence.internal.jpa.weaving]
* javadoc:org.eclipse.persistence.internal.libraries.antlr.runtime[org.eclipse.persistence.internal.libraries.antlr.runtime]
* javadoc:org.eclipse.persistence.internal.libraries.antlr.runtime.debug[org.eclipse.persistence.internal.libraries.antlr.runtime.debug]
* javadoc:org.eclipse.persistence.internal.libraries.antlr.runtime.misc[org.eclipse.persistence.internal.libraries.antlr.runtime.misc]
* javadoc:org.eclipse.persistence.internal.libraries.antlr.runtime.tree[org.eclipse.persistence.internal.libraries.antlr.runtime.tree]
* javadoc:org.eclipse.persistence.internal.libraries.asm[org.eclipse.persistence.internal.libraries.asm]
* javadoc:org.eclipse.persistence.internal.libraries.asm.commons[org.eclipse.persistence.internal.libraries.asm.commons]
* javadoc:org.eclipse.persistence.internal.libraries.asm.signature[org.eclipse.persistence.internal.libraries.asm.signature]
* javadoc:org.eclipse.persistence.internal.libraries.asm.tree[org.eclipse.persistence.internal.libraries.asm.tree]
* javadoc:org.eclipse.persistence.internal.libraries.asm.tree.analysis[org.eclipse.persistence.internal.libraries.asm.tree.analysis]
* javadoc:org.eclipse.persistence.internal.libraries.asm.util[org.eclipse.persistence.internal.libraries.asm.util]
* javadoc:org.eclipse.persistence.internal.libraries.asm.xml[org.eclipse.persistence.internal.libraries.asm.xml]
* javadoc:org.eclipse.persistence.internal.localization[org.eclipse.persistence.internal.localization]
* javadoc:org.eclipse.persistence.internal.localization.i18n[org.eclipse.persistence.internal.localization.i18n]
* javadoc:org.eclipse.persistence.internal.oxm[org.eclipse.persistence.internal.oxm]
* javadoc:org.eclipse.persistence.internal.oxm.accessor[org.eclipse.persistence.internal.oxm.accessor]
* javadoc:org.eclipse.persistence.internal.oxm.conversion[org.eclipse.persistence.internal.oxm.conversion]
* javadoc:org.eclipse.persistence.internal.oxm.documentpreservation[org.eclipse.persistence.internal.oxm.documentpreservation]
* javadoc:org.eclipse.persistence.internal.oxm.mappings[org.eclipse.persistence.internal.oxm.mappings]
* javadoc:org.eclipse.persistence.internal.oxm.record[org.eclipse.persistence.internal.oxm.record]
* javadoc:org.eclipse.persistence.internal.oxm.record.deferred[org.eclipse.persistence.internal.oxm.record.deferred]
* javadoc:org.eclipse.persistence.internal.oxm.record.json[org.eclipse.persistence.internal.oxm.record.json]
* javadoc:org.eclipse.persistence.internal.oxm.record.namespaces[org.eclipse.persistence.internal.oxm.record.namespaces]
* javadoc:org.eclipse.persistence.internal.oxm.schema[org.eclipse.persistence.internal.oxm.schema]
* javadoc:org.eclipse.persistence.internal.oxm.schema.model[org.eclipse.persistence.internal.oxm.schema.model]
* javadoc:org.eclipse.persistence.internal.oxm.unmapped[org.eclipse.persistence.internal.oxm.unmapped]
* javadoc:org.eclipse.persistence.internal.platform.database[org.eclipse.persistence.internal.platform.database]
* javadoc:org.eclipse.persistence.internal.queries[org.eclipse.persistence.internal.queries]
* javadoc:org.eclipse.persistence.internal.security[org.eclipse.persistence.internal.security]
* javadoc:org.eclipse.persistence.internal.sequencing[org.eclipse.persistence.internal.sequencing]
* javadoc:org.eclipse.persistence.internal.sessions[org.eclipse.persistence.internal.sessions]
* javadoc:org.eclipse.persistence.internal.sessions.coordination[org.eclipse.persistence.internal.sessions.coordination]
* javadoc:org.eclipse.persistence.internal.sessions.coordination.broadcast[org.eclipse.persistence.internal.sessions.coordination.broadcast]
* javadoc:org.eclipse.persistence.internal.sessions.coordination.corba[org.eclipse.persistence.internal.sessions.coordination.corba]
* javadoc:org.eclipse.persistence.internal.sessions.coordination.corba.sun[org.eclipse.persistence.internal.sessions.coordination.corba.sun]
* javadoc:org.eclipse.persistence.internal.sessions.coordination.jms[org.eclipse.persistence.internal.sessions.coordination.jms]
* javadoc:org.eclipse.persistence.internal.sessions.coordination.rmi[org.eclipse.persistence.internal.sessions.coordination.rmi]
* javadoc:org.eclipse.persistence.internal.sessions.coordination.rmi.iiop[org.eclipse.persistence.internal.sessions.coordination.rmi.iiop]
* javadoc:org.eclipse.persistence.internal.sessions.factories[org.eclipse.persistence.internal.sessions.factories]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model[org.eclipse.persistence.internal.sessions.factories.model]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.event[org.eclipse.persistence.internal.sessions.factories.model.event]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.log[org.eclipse.persistence.internal.sessions.factories.model.log]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.login[org.eclipse.persistence.internal.sessions.factories.model.login]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.platform[org.eclipse.persistence.internal.sessions.factories.model.platform]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.pool[org.eclipse.persistence.internal.sessions.factories.model.pool]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.project[org.eclipse.persistence.internal.sessions.factories.model.project]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.property[org.eclipse.persistence.internal.sessions.factories.model.property]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.rcm[org.eclipse.persistence.internal.sessions.factories.model.rcm]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.rcm.command[org.eclipse.persistence.internal.sessions.factories.model.rcm.command]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.sequencing[org.eclipse.persistence.internal.sessions.factories.model.sequencing]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.session[org.eclipse.persistence.internal.sessions.factories.model.session]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.transport[org.eclipse.persistence.internal.sessions.factories.model.transport]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.transport.discovery[org.eclipse.persistence.internal.sessions.factories.model.transport.discovery]
* javadoc:org.eclipse.persistence.internal.sessions.factories.model.transport.naming[org.eclipse.persistence.internal.sessions.factories.model.transport.naming]
* javadoc:org.eclipse.persistence.internal.sessions.remote[org.eclipse.persistence.internal.sessions.remote]
* javadoc:org.eclipse.persistence.jpa.dynamic[org.eclipse.persistence.jpa.dynamic]
* javadoc:org.eclipse.persistence.jpa.jpql[org.eclipse.persistence.jpa.jpql]
* javadoc:org.eclipse.persistence.jpa.jpql.parser[org.eclipse.persistence.jpa.jpql.parser]
* javadoc:org.eclipse.persistence.jpa.jpql.tools[org.eclipse.persistence.jpa.jpql.tools]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.model[org.eclipse.persistence.jpa.jpql.tools.model]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.model.query[org.eclipse.persistence.jpa.jpql.tools.model.query]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.resolver[org.eclipse.persistence.jpa.jpql.tools.resolver]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.spi[org.eclipse.persistence.jpa.jpql.tools.spi]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.utility[org.eclipse.persistence.jpa.jpql.tools.utility]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.utility.filter[org.eclipse.persistence.jpa.jpql.tools.utility.filter]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.utility.iterable[org.eclipse.persistence.jpa.jpql.tools.utility.iterable]
* javadoc:org.eclipse.persistence.jpa.jpql.tools.utility.iterator[org.eclipse.persistence.jpa.jpql.tools.utility.iterator]
* javadoc:org.eclipse.persistence.jpa.jpql.utility[org.eclipse.persistence.jpa.jpql.utility]
* javadoc:org.eclipse.persistence.jpa.jpql.utility.filter[org.eclipse.persistence.jpa.jpql.utility.filter]
* javadoc:org.eclipse.persistence.jpa.jpql.utility.iterable[org.eclipse.persistence.jpa.jpql.utility.iterable]
* javadoc:org.eclipse.persistence.jpa.jpql.utility.iterator[org.eclipse.persistence.jpa.jpql.utility.iterator]
* javadoc:org.eclipse.persistence.jpa.metadata[org.eclipse.persistence.jpa.metadata]
* javadoc:org.eclipse.persistence.logging[org.eclipse.persistence.logging]
* javadoc:org.eclipse.persistence.mappings[org.eclipse.persistence.mappings]
* javadoc:org.eclipse.persistence.mappings.converters[org.eclipse.persistence.mappings.converters]
* javadoc:org.eclipse.persistence.mappings.foundation[org.eclipse.persistence.mappings.foundation]
* javadoc:org.eclipse.persistence.mappings.querykeys[org.eclipse.persistence.mappings.querykeys]
* javadoc:org.eclipse.persistence.mappings.structures[org.eclipse.persistence.mappings.structures]
* javadoc:org.eclipse.persistence.mappings.transformers[org.eclipse.persistence.mappings.transformers]
* javadoc:org.eclipse.persistence.mappings.xdb[org.eclipse.persistence.mappings.xdb]
* javadoc:org.eclipse.persistence.oxm[org.eclipse.persistence.oxm]
* javadoc:org.eclipse.persistence.oxm.annotations[org.eclipse.persistence.oxm.annotations]
* javadoc:org.eclipse.persistence.oxm.attachment[org.eclipse.persistence.oxm.attachment]
* javadoc:org.eclipse.persistence.oxm.documentpreservation[org.eclipse.persistence.oxm.documentpreservation]
* javadoc:org.eclipse.persistence.oxm.mappings[org.eclipse.persistence.oxm.mappings]
* javadoc:org.eclipse.persistence.oxm.mappings.converters[org.eclipse.persistence.oxm.mappings.converters]
* javadoc:org.eclipse.persistence.oxm.mappings.nullpolicy[org.eclipse.persistence.oxm.mappings.nullpolicy]
* javadoc:org.eclipse.persistence.oxm.platform[org.eclipse.persistence.oxm.platform]
* javadoc:org.eclipse.persistence.oxm.record[org.eclipse.persistence.oxm.record]
* javadoc:org.eclipse.persistence.oxm.schema[org.eclipse.persistence.oxm.schema]
* javadoc:org.eclipse.persistence.oxm.sequenced[org.eclipse.persistence.oxm.sequenced]
* javadoc:org.eclipse.persistence.oxm.unmapped[org.eclipse.persistence.oxm.unmapped]
* javadoc:org.eclipse.persistence.platform.database[org.eclipse.persistence.platform.database]
* javadoc:org.eclipse.persistence.platform.database.converters[org.eclipse.persistence.platform.database.converters]
* javadoc:org.eclipse.persistence.platform.database.events[org.eclipse.persistence.platform.database.events]
* javadoc:org.eclipse.persistence.platform.database.jdbc[org.eclipse.persistence.platform.database.jdbc]
* javadoc:org.eclipse.persistence.platform.database.oracle.annotations[org.eclipse.persistence.platform.database.oracle.annotations]
* javadoc:org.eclipse.persistence.platform.database.oracle.jdbc[org.eclipse.persistence.platform.database.oracle.jdbc]
* javadoc:org.eclipse.persistence.platform.database.oracle.plsql[org.eclipse.persistence.platform.database.oracle.plsql]
* javadoc:org.eclipse.persistence.platform.database.partitioning[org.eclipse.persistence.platform.database.partitioning]
* javadoc:org.eclipse.persistence.platform.server[org.eclipse.persistence.platform.server]
* javadoc:org.eclipse.persistence.platform.xml[org.eclipse.persistence.platform.xml]
* javadoc:org.eclipse.persistence.platform.xml.jaxp[org.eclipse.persistence.platform.xml.jaxp]
* javadoc:org.eclipse.persistence.sequencing[org.eclipse.persistence.sequencing]
* javadoc:org.eclipse.persistence.services[org.eclipse.persistence.services]
* javadoc:org.eclipse.persistence.services.websphere[org.eclipse.persistence.services.websphere]
* javadoc:org.eclipse.persistence.sessions.broker[org.eclipse.persistence.sessions.broker]
* javadoc:org.eclipse.persistence.sessions.changesets[org.eclipse.persistence.sessions.changesets]
* javadoc:org.eclipse.persistence.sessions.coordination[org.eclipse.persistence.sessions.coordination]
* javadoc:org.eclipse.persistence.sessions.coordination.broadcast[org.eclipse.persistence.sessions.coordination.broadcast]
* javadoc:org.eclipse.persistence.sessions.coordination.corba[org.eclipse.persistence.sessions.coordination.corba]
* javadoc:org.eclipse.persistence.sessions.coordination.corba.sun[org.eclipse.persistence.sessions.coordination.corba.sun]
* javadoc:org.eclipse.persistence.sessions.coordination.jms[org.eclipse.persistence.sessions.coordination.jms]
* javadoc:org.eclipse.persistence.sessions.coordination.rmi[org.eclipse.persistence.sessions.coordination.rmi]
* javadoc:org.eclipse.persistence.sessions.factories[org.eclipse.persistence.sessions.factories]
* javadoc:org.eclipse.persistence.sessions.interceptors[org.eclipse.persistence.sessions.interceptors]
* javadoc:org.eclipse.persistence.sessions.remote[org.eclipse.persistence.sessions.remote]
* javadoc:org.eclipse.persistence.sessions.remote.corba.sun[org.eclipse.persistence.sessions.remote.corba.sun]
* javadoc:org.eclipse.persistence.sessions.remote.rmi[org.eclipse.persistence.sessions.remote.rmi]
* javadoc:org.eclipse.persistence.sessions.remote.rmi.iiop[org.eclipse.persistence.sessions.remote.rmi.iiop]
* javadoc:org.eclipse.persistence.sessions.serializers[org.eclipse.persistence.sessions.serializers]
* javadoc:org.eclipse.persistence.sessions.server[org.eclipse.persistence.sessions.server]
* javadoc:org.eclipse.persistence.tools[org.eclipse.persistence.tools]
* javadoc:org.eclipse.persistence.tools.file[org.eclipse.persistence.tools.file]
* javadoc:org.eclipse.persistence.tools.profiler[org.eclipse.persistence.tools.profiler]
* javadoc:org.eclipse.persistence.tools.schemaframework[org.eclipse.persistence.tools.schemaframework]
* javadoc:org.eclipse.persistence.tools.tuning[org.eclipse.persistence.tools.tuning]
* javadoc:org.eclipse.persistence.tools.weaving.jpa[org.eclipse.persistence.tools.weaving.jpa]
* javadoc:org.eclipse.persistence.transaction[org.eclipse.persistence.transaction]
* javadoc:org.eclipse.persistence.transaction.was[org.eclipse.persistence.transaction.was]

== Feature configuration elements
* config:classloading[classloading]
* config:transaction[transaction]
