= Database Session Persistence 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables persistence of HTTP sessions to a datasource using JDBC. Persisting HTTP session data to a database allows recovery of the data after a server restart or unexpected server failure. Failover of HTTP sessions can be achieved by configuring multiple servers to persist data to the same location

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Database Session Persistence 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>sessionDatabase-1.0</feature>
----
// end::enable[]
// tag::config[]

== Feature configuration elements
* config:classloading[]
* config:httpSession[]
* config:httpSessionDatabase[]
* config:transaction[]
// end::config[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:jdbc-4.0[]
* feature:jdbc-4.1[]
* feature:jdbc-4.2[]
* feature:jdbc-4.3[]
* feature:jndi-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Database Session Persistence 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.sessionDatabase-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
