= Spring Boot Support version 1.5
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables support for Spring Boot applications using Spring Boot version 1.5.x. 

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Spring Boot Support version 1.5 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>springBoot-1.5</feature>
----
// end::enable[]
// tag::config[]

== Feature configuration elements
* config:application[]
* config:applicationManager[]
* config:applicationMonitor[]
* config:classloading[]
* config:javaPermission[]
* config:library[]
* config:springBootApplication[]
// end::config[]
// tag::apis[]
// end::apis[]
// tag::requirements[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Spring Boot Support version 1.5 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.springBoot-1.5; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
