= Transport Security 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

// tag::description[]
This feature enables support for Secure Sockets Layer (SSL) connections. The secure HTTPS listener is not started unless the transportSecurity-1.0 feature is enabled and a keystore is configured.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Transport Security 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>transportSecurity-1.0</feature>
----
// end::enable[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:ssl-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Transport Security 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.transportSecurity-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]
