= Message Server 1.0
:stylesheet: ../feature.css
:linkcss: 
:page-layout: feature
:nofooter: 

This feature enables an embedded messaging server that is JMS compliant. Applications can send and receive messages using the wasJmsClient feature.

== Enabling this feature
To enable the Message Server 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>wasJmsServer-1.0</feature>
----

== Supported Java versions

* JavaSE-1.7
* JavaSE-1.8

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Message Server 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.wasJmsServer-1.0; type="osgi.subsystem.feature"
----

== Features that enable this feature
* feature:javaee-7.0[]
* feature:javaee-8.0[]

== IBM API packages provided by this feature
* javadoc:com.ibm.websphere.messaging.mbean[]

== Feature configuration elements
* config:channelfw[]
* config:classloading[]
* config:messagingEngine[]
* config:tcpOptions[]
* config:transaction[]
* config:wasJmsEndpoint[]
* config:wasJmsOutbound[]
