apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        # tag::sysImage[]
        image: gcr.io/[project-id]/system:1.0-SNAPSHOT
        # end::sysImage[]
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        # tag::invImage[]
        image: gcr.io/[project-id]/inventory:1.0-SNAPSHOT
        # end::invImage[]
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  # tag::sysNodePort[]
  type: NodePort
  # end::sysNodePort[]
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  # tag::invNodePort[]
  type: NodePort
  # end::invNodePort[]
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32000