apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  # tag::labels1[]
  labels:
  # end::labels1[]
    # tag::app1[]
    app: system
    # end::app1[]
spec:
  selector:
    matchLabels:
      # tag::app2[]
      app: system
      # end::app2[]
  # tag::rolling1[]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # tag::maxUnavailable1[]
      maxUnavailable: 1
      # end::maxUnavailable1[]
      # tag::maxSurge1[]
      maxSurge: 1
      # end::maxSurge1[]
  # end::rolling1[]
  template:
    metadata:
      # tag::labels2[]
      labels:
      # end::labels2[]
        # tag::app3[]
        app: system
        # end::app3[]
    spec:
      containers:
      - name: system-container
        # tag::image1[]
        image: system:1.0-SNAPSHOT
        # end::image1[]
        ports:
        # tag::containerPort1[]
        - containerPort: 9080
        # end::containerPort1[]
        # tag::readinessProbe1[]
        readinessProbe:
          httpGet:
            # tag::ready1[]
            path: /health/ready
            # end::ready1[]
            port: 9080
          # tag::delay2[]
          initialDelaySeconds: 30
          # end::delay2[]
          # tag::period2[]
          periodSeconds: 10
          # end::period2[]
          # tag::timeout2[]
          timeoutSeconds: 3
          # end::timeout2[]
          # tag::threshold2[]
          failureThreshold: 1
          # end::threshold2[]
        # end::readinessProbe1[]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  # tag::labels3[]
  labels:
  # end::labels3[]
    # tag::app4[]
    app: inventory
    # end::app4[]
spec:
  selector:
    matchLabels:
      # tag::app5[]
      app: inventory
      # end::app5[]
  # tag::rolling2[]
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # tag::maxUnavailable2[]
      maxUnavailable: 1
      # end::maxUnavailable2[]
      # tag::maxSurge2[]
      maxSurge: 1
      # end::maxSurge2[]    
  # end::rolling2[]
  template:
    metadata:
      # tag::labels4[]
      labels:
      # end::labels4[]
        # tag::app6[]
        app: inventory
        # end::app6[]
    spec:
      containers:
      - name: inventory-container
        # tag::image2[]
        image: inventory:1.0-SNAPSHOT
        # end::image2[]
        ports:
        # tag::containerPort2[]
        - containerPort: 9080
        # end::containerPort2[]
        env:
        - name: SYS_APP_HOSTNAME
          value: system-service
        # tag::readinessProbe2[]
        readinessProbe:
          httpGet:
            # tag::ready2[]
            path: /health/ready
            # end::ready2[]
            port: 9080
          # tag::delay4[]
          initialDelaySeconds: 30
          # end::delay4[]
          # tag::period4[]
          periodSeconds: 10
          # end::period4[]
          # tag::timeout4[]
          timeoutSeconds: 3
          # end::timeout4[]
          # tag::threshold4[]
          failureThreshold: 1
          # end::threshold4[]
        # end::readinessProbe2[]
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  # tag::NodePort1[]
  type: NodePort
  # end::NodePort1[]
  selector:
    # tag::app7[]
    app: system
    # end::app7[]
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    # tag::nodePort1[]
    nodePort: 31000
    # end::nodePort1[]

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  # tag::NodePort2[]
  type: NodePort
  # end::NodePort2[]
  selector:
    # tag::app8[]
    app: inventory
    # end::app8[]
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    # tag::nodePort2[]
    nodePort: 32000
    # end::nodePort2[]
