apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      # tag::system-container[]
      - name: system-container
        image: system:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        # system probes
        startupProbe:
          httpGet:
            path: /health/started
            port: 9080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        readinessProbe:
           httpGet:
            path: /health/ready
            port: 9080
           initialDelaySeconds: 30
           periodSeconds: 10
           timeoutSeconds: 3
           failureThreshold: 1
        # Set the environment variables
        # tag::env1[]
        env:
        # end::env1[]
        # tag::contextRoot1[]
        - name: CONTEXT_ROOT
          # tag::valueFrom1[]
          valueFrom:
          # end::valueFrom1[]
            # tag::configRef1[]
            configMapKeyRef:
              # tag::root1[]
              name: sys-app-root
              # end::root1[]
              # tag::contextRootKey1[]
              key: contextRoot
              # end::contextRootKey1[]
            # end::configRef1[]
        # end::contextRoot1[]
        # tag::sysUsername1[]
        - name: SYSTEM_APP_USERNAME
          # tag::valueFrom2[]
          valueFrom:
          # end::valueFrom2[]
            # tag::secretRef1[]
            secretKeyRef:
              # tag::credentials1[]
              name: sys-app-credentials
              # end::credentials1[]
              # tag::username1[]
              key: username
              # end::username1[]
            # end::secretRef1[]
        # end::sysUsername1[]
        # tag::sysPassword1[]
        - name: SYSTEM_APP_PASSWORD
          # tag::valueFrom3[]
          valueFrom:
          # end::valueFrom3[]
            # tag::secretRef2[]
            secretKeyRef:
              # tag::credentials2[]
              name: sys-app-credentials
              # end::credentials2[]
              # tag::password1[]
              key: password
              # end::password1[]
            # end::secretRef2[]
        # end::sysPassword1[]
      # end::system-container[]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      # tag::inventory-container[]
      - name: inventory-container
        image: inventory:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        # inventory probes
        startupProbe:
          httpGet:
            path: /health/started
            port: 9080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        # Set the environment variables
        # tag::env2[]
        env:
        # end::env2[]
        - name: SYS_APP_HOSTNAME
          value: system-service
        # tag::contextRoot2[]
        - name: CONTEXT_ROOT
          # tag::valueFrom4[]
          valueFrom:
          # end::valueFrom4[]
            # tag::configRef2[]
            configMapKeyRef:
              # tag::root2[]
              name: sys-app-root
              # end::root2[]
              # tag::contextRootKey2[]
              key: contextRoot
              # end::contextRootKey2[]
            # end::configRef2[]
        # end::contextRoot2[]
        # tag::sysUsername2[]
        - name: SYSTEM_APP_USERNAME
          # tag::valueFrom5[]
          valueFrom:
          # end::valueFrom5[]
            # tag::secretRef3[]
            secretKeyRef:
              # tag::credentials3[]
              name: sys-app-credentials
              # end::credentials3[]
              # tag::username2[]
              key: username
              # end::username2[]
            # end::secretRef3[]
        # end::sysUsername2[]
        # tag::sysPassword2[]
        - name: SYSTEM_APP_PASSWORD
          # tag::valueFrom6[]
          valueFrom:
          # end::valueFrom6[]
            # tag::secretRef4[]
            secretKeyRef:
              # tag::credentials4[]
              name: sys-app-credentials
              # end::credentials4[]
              # tag::password2[]
              key: password
              # end::password2[]
            # end::secretRef4[]
        # end::sysPassword2[]
      # end::inventory-container[]
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32000
