# This script contains the end-to-end steps for building the website with Jekyll and using Maven to package
# Exit immediately if a simple command exits with a non-zero status.
set -e

./scripts/build_gem_dependencies.sh

echo "Ruby version:"
echo `ruby -v`

echo "npm version:"
echo `npm -v`

# Install Antora on the machine
npm i -g @antora/cli@2.3

npm i @antora/site-generator-default@2.3

# Guides that are ready to be published to openliberty.io
echo "Cloning repositories with name starting with guide or iguide..."
ruby ./scripts/build_clone_guides.rb

# Development environment only actions
if [ "$JEKYLL_ENV" != "production" ]; then 
    echo "Not in production environment..."
    echo "Adding robots.txt"
    cp robots.txt src/main/content/robots.txt

    # Development environments with draft docs/guides
    if [ "$JEKYLL_DRAFT_GUIDES" == "true" ]; then
        echo "Clone draft guides for test environments..."
        ruby ./scripts/build_clone_guides.rb "draft-guide"    

        # Need to make sure there are draft-iguide* folders before using the find command
        # If we don't, the find command will fail because the path does not exist
        if [ $(find src/main/content/guides -type d -name "draft-iguide*" | wc -l ) != "0" ] ; then
            echo "Moving any js and css files from draft interactive guides..."
            find src/main/content/guides/draft-iguide* -d -name js -exec cp -R '{}' src/main/content/_assets \;
            find src/main/content/guides/draft-iguide* -d -name css -exec cp -R '{}' src/main/content/_assets \;
        fi
    fi
else
    # Production!
    echo "Clone published certifications!"
    ./scripts/build_clone_certifications.sh "master" # Argument is branch name of OpenLiberty/certifications
fi

# Clone docs repo
./scripts/build_clone_docs.sh "antora"

pushd gems/ol-asciidoc
gem build ol-asciidoc.gemspec
gem install ol-asciidoc-0.0.1.gem
popd

# Special external link handling
pushd gems/ol-target-blank
gem build ol-target-blank.gemspec
gem install ol-target-blank-0.0.1.gem
popd

echo "Copying guide images to /img/guide"
mkdir -p src/main/content/img/guide

# Find images in draft guides and copy to img/guide/{projectid}
find src/main/content/guides/draft-guide*/assets/* | while read line; do
    imgPath=$(echo "$line" | sed -e 's/guides\/draft-guide-/img\/guide\//g' | sed 's/\/assets\/.*//g')
    mkdir -p $imgPath && cp -R $line "$_"
done

# Find images in published guides and copy to img/guide/{projectid}
find src/main/content/guides/guide*/assets/* | while read line; do
    imgPath=$(echo "$line" | sed -e 's/guides\/guide-/img\/guide\//g' | sed 's/\/assets\/.*//g')
    mkdir -p $imgPath && cp -R $line "$_"
done

# Move any js/css files from guides to the _assets folder for jekyll-assets minification.
echo "Moving any js and css files published interactive guides..."
# Assumption: There is _always_ iguide* folders
find src/main/content/guides/iguide* -d -name js -exec cp -R '{}' src/main/content/_assets \;
find src/main/content/guides/iguide* -d -name css -exec cp -R '{}' src/main/content/_assets \;

# Build draft and published blogs
./scripts/build_clone_blogs.sh

# Jekyll build
echo "Building with jekyll..."
echo `jekyll -version`
mkdir -p target/jekyll-webapp

# Enable google analytics if ga is true
if [ "$ga" = true ]
  then 
    jekyll build --source src/main/content --config src/main/content/_config.yml,src/main/content/_google_analytics.yml --destination target/jekyll-webapp 
  else
    # Set the --future flag to show blogs with date timestamps in the future
    jekyll build --future --source src/main/content --destination target/jekyll-webapp 
fi

# Install Antora packages and build the Antora UI bundle
./scripts/build_antora_ui.sh

# Use the Antora playbook to download the docs and build the doc pages
./scripts/build_clone_antora_playbook.sh

echo "Using the Antora playbook to generate what content to display for docs"
antora --fetch --stacktrace src/main/content/docs/antora-playbook.yml

# Copy the contents generated by Antora to the website folder
echo "Moving the Antora docs to the jekyll webapp"
mkdir -p target/jekyll-webapp/docs/
cp -r src/main/content/docs/build/site/. target/jekyll-webapp/

# python3 ./scripts/parse-feature-toc.py

# Maven packaging
# A Maven wrapper is used to set our own Maven version independent of the build environment and is specified in ./mvn/wrapper/maven-wrapper.properties
# Set the TLS Protocol to 1.2 for the maven wrapper on Java version 1.7
echo "Running maven (mvn)..."
./mvnw -B -Dhttps.protocols=TLSv1.2 package
