---
layout: post
title: "The boost-maven-plugin: An easy way to build layered Docker images of Spring Boot apps"
date:   2018-09-12 10:20:00 -0000
categories: blog
seo-title: The boost-maven-plugin: An easy way to build layered Docker images of Spring Boot apps - OpenLiberty.io
seo-description: A simple and efficient way of building and pushing layered Docker images of Spring Boot applications using Boost Maven Plugin.
blog_description: "A simple and efficient way of building and pushing layered Docker images of Spring Boot applications using Boost Maven Plugin".
---


= The boost-maven-plugin: An easy way to build layered Docker images of Spring Boot apps
Anjum Fatima <https://github.com/anjumfatima90>

Do you find writing Dockerfiles difficult, but want an efficient docker image of your
Spring Boot application? Do you want a maven plugin to do your job?
If the answer is yes, you are at right place.

Writing a Dockerfile to create an efficient Docker image can be a challenging task.
It requires, understanding techniques to optimize Dockerfiles. Boost Maven plugin
provides a functionality to build and push efficient Docker images of Spring Boot
applications using Liberty.

In the blog post link:blog/2018/07/02/creating-dual-layer-docker-images-for-spring-boot-apps.html[Creating Dual Layer Docker images for Spring Boot apps],
the steps to create an efficient docker image was shown, but to improve the user experience
we built a maven plugin that can easily be configured into your Spring Boot application, to
build and push efficient Docker images without the hassle of writing Dockerfiles.

**Note** : The boost-maven-plugin is in its beta stage. 

== Steps to configure Boost Maven plugin

You can configure the `boost-maven-plugin` in the `plugins` section of the pom.xml
of your Spring Boot application as shown below:
----
<plugin>
  <groupId>io.openliberty.boost</groupId>
  <artifactId>boost-maven-plugin</artifactId>
  <version>0.1</version>
</plugin>
----

It requires minimal knowledge of Docker including installing and running Docker on your machine.

NOTE: `spring-boot-maven-plugin` must be configured before this plugin in order to create the required executable archive
of the application.


=== Build Docker image

To build a docker image you can add execution goal to the plugin inside pom.xml like:
----
<plugin>
  <groupId>io.openliberty.boost</groupId>
  <artifactId>boost-maven-plugin</artifactId>
  <version>0.1</version>
  <executions>
    <execution>
      <goals>
        <goal>docker-build</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----
`mvn clean package` will create a docker image with a default repository name as `${project.artifactId}`
 and a default tag `latest`.

Alternatively, you can configure the plugin with no execution goals and do the following steps:

`mvn clean package`

`mvn boost:docker-build`

NOTE: The docker-build goal creates a Liberty specific Dockerfile in the root folder of the Spring Boot project
in the absence of a Dockerfile and builds the docker image.


=== Push Docker image

In order to push an image to a public or private registry, you need to configure the `repository` parameter
in the format `[REGISTRYHOST/][USERNAME/]NAME`. The tag parameter is set to `latest` by default.

You can configure the plugin as below:
----
<plugin>
  <groupId>io.openliberty.boost</groupId>
  <artifactId>boost-maven-plugin</artifactId>
  <version>0.1</version>
  <configuration>
    <repository>[your_domain_name]/${project.artifactId}</repository>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>docker-build</goal>
        <goal>docker-push</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

`mvn clean install` will create an image with the given `repository` name with default tag `latest` and push the image to the registry.

Alternatively, you can configure the plugin with no execution goals and do the following steps:

`mvn clean package`

`mvn boost:docker-build`

`mvn boost:docker-push`


*Note* :

For public registry like Docker Hub, replace `[your_domain_name]` with your Docker Hub username.

For private registry like IBM Container registry, replace `[your_domain_name]` with with your IBM Container Registry Host. For example, `registry.ng.bluemix.net`.

== Authentication required to push Docker Image

For `docker-push` goal to work, authentication is required.

**You can provide credentials in Maven settings.xml file.**

  <server>
    <id>[your_registry_id]</id>
    <username>[your_registry_username]</username>
    <password>[your_registry_password]</password>
  </server>

Example :

For public registry like Docker Hub,

----
<server>
  <id>docker.io</id>
  <username>[your_registry_username]</username>
  <password>[your_registry_password]</password>
</server>
----


For private registry like IBM Container Registry,[1]

----
<server>
  <id>registry.ng.bluemix.net</id>
  <username>token</username>
  <password>[your_registry_token]</password>
</server>
----

**Alternatively, you can provide credentials by doing a docker login.**

This stores the credentials in the default docker config location `~/.docker/config.json`.

Example:

For public registry like Docker Hub,

----
docker login
----

For private registry like IBM Container Registry, [1]

----
docker login -u token -p [your_registry_token] registry.ng.bluemix.net
----


== References
[1] https://docs.docker.com/v17.09/docker-for-ibm-cloud/ibm-registry/
