---
layout: post
title: Post title here.

categories: blog
author_picture: https://avatars.github.ibm.com/u/38675
seo-title: Title here - OpenLiberty.io. Used in search results and on social media.
seo-description: Active description of the post - 50–300 characters. This is used in search results and on social media.
blog_description: "Blog preview description. ~60 words - this is used in the preview card on openliberty.io/blog"
---
= Dynamically update your microservice configuration
Neil Young <https://github.ibm.com/neil-young>

Most applications require configuration that is specific to the environment in which they run. Different environments require different configurations and it is highly desirable not to have to rebuild and repackage applications for each different case. MicroProfile Config allows you to separate configuration from microservices code so that the values required by the service can be maintained externally to the code. The configuration data can come from different locations and in different formats, for example from system properties and system environment variables. The `mpConfig-1.3` feature now allows you to easily and dynamically change your application’s configuration by adding or modifying variables in the Liberty `server.xml` file.

In addition, Liberty builds on previous versions of MicroProfile Config with enhancements in the areas of implicit converters and the mapping of config properties to environment variables. You can use this feature with either the `cdi-1.2` feature or the `cdi-2.0` feature.

To enable the MicroProfile Config 1.3 feature, add it to the `server.xml`:

[source,xml]
----
<featureManager>
  <feature>mpConfig-1.3</feature>
</featureManager>
----

== Define configuration in the server.xml

Define a MicroProfile application's configuration through the Liberty `server.xml` file. Use the variable element in the `server.xml` to assign a value to a configuration entity that can be accessed by any application running on the server:

[source,xml]
----
<variable name="varServerXMLKey1" value="valueinVarServerXMLVariable1" />
----

Alternatively, use the `appProperties` property element to assign a value to a configuration entity that can be accessed by a specific application:
 
[source,xml]
----
    <application location="variableServerXMLApp.war">
        <appProperties>
             <property name="appServerXMLKey1" value="valueinAppProperties1"/>
        </appProperties>
    </application>
----

The `appProperties` element can be specified in either an `application` or a `webApplication` element.


== Implicit converter improvements

The implicit converters have been improved so that if no built-in nor custom converter is available for a requested Type T, an implicit converter is automatically provided in any of the following situations:

* The target type `T` has a `public static T of(String)` method.
* The target type `T` has a `public static T valueOf(String)` method.
* The target type `T` has a public Constructor with a String parameter.
* The target type `T` has a `public static T parse(CharSequence)` method. This change means that some built-in converters were no longer required and have been removed.


See the GitHub issue: https://github.com/eclipse/microprofile-config/issues/325[#325].

== Mapping a config property to environment variable

Some operating systems allow only alphabetic characters or an underscore (`_`) in environment variables. Other characters such as period (`.`), forward slash (`/`), and so on may be disallowed. In order to set a value for a config property that has a name containing such disallowed characters from an environment variable, this `ConfigSource` searches 3 environment variables for a given property name (e.g. `com.ACME.size`) and the first environment variable found is returned:

* Exact match (i.e. `com.ACME.size`)
* Replace the character that is neither alphanumeric nor an underscore with an underscore (`_`) (i.e. `com_ACME_size`)
* Replace the character that is neither alphanumeric nor an underscore with an underscore (`_`) and convert to upper case (i.e. `COM_ACME_SIZE`)


See the GitHub issue: https://github.com/eclipse/microprofile-config/issues/264[#264].

== Other changes

There were also some specification changes: https://github.com/eclipse/microprofile-config/issues/348[#348], https://github.com/eclipse/microprofile-config/issues/325[#325], https://github.com/eclipse/microprofile-config/issues/264[#264].

The API bundle can work with either CDI 1.2 or CDI 2.0 in an OSGi environment.


== Find out more

For more info:

* https://github.com/eclipse/microprofile-config/milestone/3?closed=1[Full list of changes since MicroProfile Config 1.2]
* https://www.openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices (Open Liberty interactive guide)]
* https://www.openliberty.io/guides/microprofile-config.html[Configuring microservices (Open Liberty guide)]
* https://www.eclipse.org/community/eclipse_newsletter/2017/september/article3.php[What is MicroProfile Config? (Eclipse newsletter)]
* http://microprofile.io/project/eclipse/microprofile-config[MicroProfile Config (MicroProfile.io)]
