apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        # tag::systemImage[]
        image: image-registry.openshift-image-registry.svc:5000/my-project/system:1.0-SNAPSHOT
        # end::systemImage[]
        ports:
        - containerPort: 9080
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        # tag::inventoryImage[]
        image: image-registry.openshift-image-registry.svc:5000/my-project/inventory:1.0-SNAPSHOT
        # end::inventoryImage[]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 8080
---
# tag::systemRoute[]
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: system-route
spec:
  to:
    kind: Service
    name: system-service
# end::systemRoute[]
---
# tag::inventoryRoute[]
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inventory-route
spec:
  to:
    kind: Service
    name: inventory-service
# end::inventoryRoute[]
